### ISSUE TITLE
does the chado_get_feature_sequences API return sequences in the correct order?

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#916] opened 2019-03-29 14:25 UTC
### Issue description

I'm writing code that makes use of the very convenient `chado_get_feature_sequences`.  I'm looking at a negative strand CDS, and comparing the "correct" sequence in feature.residues to that returned with the `derive_from_parent` option... and the two appear to be at odds.

![Screen Shot 2019-03-29 at 10 21 49 AM](https://user-images.githubusercontent.com/7063154/55239228-96869b80-520c-11e9-87e5-a74f058e0352.png)
As you can see the98 residues in the first region of the array (featureloc 7040905) are actually the last sequences in the true CDS.

If we look in featureloc, we can see that `7040905` is rank 12, ie, the last sequence.  So, why would it be returned first?  Furthermore `chado_get_feature_sequences` doesnt return the rank, so if i wanted to sort this out, i would have to look up each featureloc's rank individually.

```
elect * from chado.featureloc where feature_id = 7008813;
featureloc_id	feature_id	srcfeature_id	fmin	is_fmin_partial	fmax	is_fmax_partial	strand	phase	residue_info	locgroup	rank
7040893	7008813	975356	3648415	f	3648461	f	-1			0	0
7040894	7008813	975356	3635541	f	3635664	f	-1	2		0	1
7040895	7008813	975356	3635159	f	3635323	f	-1	2		0	2
7040896	7008813	975356	3634938	f	3635074	f	-1			0	3
7040897	7008813	975356	3633244	f	3633426	f	-1	2		0	4
7040898	7008813	975356	3628725	f	3628900	f	-1			0	5
7040899	7008813	975356	3626756	f	3626970	f	-1	2		0	6
7040900	7008813	975356	3626489	f	3626655	f	-1	1		0	7
7040901	7008813	975356	3626111	f	3626238	f	-1			0	8
7040902	7008813	975356	3625903	f	3626057	f	-1	2		0	9
7040903	7008813	975356	3624747	f	3624979	f	-1	1		0	10
7040904	7008813	975356	3624471	f	3624691	f	-1			0	11
7040905	7008813	975356	3624187	f	3624285	f	-1	2		0	12
````
we note that 3624187 is the far 3' end of the sequence, and 3648415 the far 5' end.    So, for a negative strand sequence, we would put the 5' end first, ie, rank 0, which is being put last.  I am wondering if for negative strand sequences its going from high to low rank, instead of based on the fmin/fmax, and the source GFF isnt what Tripal is expecting, something like that?  It's deriving the correct subfeature sequences, just putting them together in the wrong order.

Here's the code i used to demonstrate the sequences:

```php

$options = [];


$residues_seq = chado_get_feature_sequences(['feature_id' => 7008813], $options);

dpm($residues_seq[0]['residues']);


$options['derive_from_parent'] = 1;

$derived_array = chado_get_feature_sequences(['feature_id' => 7008813], $options);


foreach ($derived_array as $sequence) {
  dpm($sequence);
}
```

**Comment by bradfordcondon** [comment] 2019-04-01 15:48
i see this was specifically fixed in https://github.com/tripal/tripal/issues/415

i wonder if the fix didnt encompass the use case of my site for whatever reason.

Here's the PR:  https://github.com/tripal/tripal/pull/667/files


```php

```

**Comment by laceysanderson** [comment] 2019-11-11 23:49
I think I've confirmed via tests that this is a bug with the `chado_get_feature_sequences()` function when negative strand derived features are supplied. You can see the tests on the `916-chado-get-feature-seqs` branch.

When inserting data to test this, I noticed the docs say ["fmin: The leftmost/minimal boundary in the linear range represented by the featureloc."](https://chado.readthedocs.io/en/rtd/_static/schemaspy_integration/tables/featureloc.html). Yet the fix in #415 implies that fmin always is the start of the sequence. This is why we're seeing this bug because on negative strands, we should be ordering by `fmax DESC` rather then `fmin ASC`.

@bradfordcondon can you check my logic in these tests? Being focused on breeding data my gene locations are a bit rusty...

**Comment by laceysanderson** [comment] 2019-11-12 01:55
Hmmmm.... according to the following comment in the code, I'm wondering if the function is doing exactly what it's designed to do -it's just not intuitive. This makes me worry that if we "fix" it, we'll actually break the Chado Fields depending on this function.

```
  // This query is meant to get all of the sub features of any given
  // feature (arg #1) and order them as they appear on the reference
  // feature (arg #2).
  $sfsql = '
    SELECT SF.feature_id, CVT.name as type_name, SF.type_id
    FROM {feature_relationship} FR
      INNER JOIN {feature} SF    ON SF.feature_id = FR.subject_id
      INNER JOIN {cvterm} CVT    ON CVT.cvterm_id = SF.type_id
      INNER JOIN {featureloc} FL ON FL.feature_id = FR.subject_id
      INNER JOIN {feature} PF    ON PF.feature_id = FL.srcfeature_id
    WHERE FR.object_id = :feature_id and PF.feature_id = :srcfeature_id
    ORDER BY FL.fmin ASC
  ';
```
https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/api/modules/tripal_chado.feature.api.inc#L318-L330

**Comment by laceysanderson** [comment] 2020-10-15 21:29
I think the solution would be to have the two ordering indicated by an option with the current "Order by Reference" being the default but "Order by Strand" being an option. Then we would also want to check that we are using the correct order for fields which use this function.

**Comment by laceysanderson** [comment] 2022-12-07 02:46
Closing this as it's now outdated with the move to Tripal 4.

**Closed as completed by laceysanderson** 2022-12-07 02:46 UTC
Labels: Community - Please Contribute, bug - potential
