### ISSUE TITLE
Publish is not publishing more than one item when cardinality is unlimited

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1843] opened 2024-04-03 16:30 UTC
### Tripal Version

4.x-dev

### Drupal Version

10.2

### PostgreSQL Version

13.14

### PHP Version

8.3

### General Description

It appears that publish is not publishing more than one item when cardinality is unlimited. Only the first one gets published.

### Steps to reproduce

1-4. Create two contacts, and two projects. Do not put a contact on the project or vice versa.
5. Generate links with this SQL: `insert into project_contact (project_id, contact_id) values (1,2), (1,3), (2,2), (2,3);`
`INSERT 0 4`
6. Publish contact and run the job
7. Publish project and run the job ~~(don't run both together because of issue #1716)~~ (fixed with PR #1841)
8. Rebuild cache `drush cache:rebuild`
9. Observe that only one contact is present on each project, only one project present on each contact.

**Comment by laceysanderson** [comment] 2024-04-28 19:01
I jumped in on this to see if I can figure out what is going on. I collaborated on @dsenalik existing branch, `tv4g1-issue1843-fix-for-cardinality-gt-1`, by bringing it up to date and expanding the findFieldItems return value. Previously this array just recorded if there was a published field item for a given field/delta. Now, it also saved the required property type values. This allows us to better confirm that the field item has in fact been published previously.

I also added some debugging so that we can see what is being published and what is being skipped, field item wise. This shows that the issue is not actually in the find/insertFieldItem functions. Rather it seems that the $matches array only includes one entry for these unlimited fields 🙈.

For example when I setup my environment as explained in this issue and then publish the contact content type repeatedly 🤪 this is the output I see on subsequent tries:
```
2024-04-28 18:58:11: Job ID 25.
2024-04-28 18:58:11: Calling: tripal_publish(contact, chado_storage, Array)
Step  1 of 6: Find matching records... 
 [notice] Step  1 of 6: Find matching records... 
Step  2 of 6: Generate page titles...
 [notice] Step  2 of 6: Generate page titles...
Step  3 of 6: Find existing published entities...
 [notice] Step  3 of 6: Find existing published entities...
Step  4 of 6: Publishing 0 new entities...
 [notice] Step  4 of 6: Publishing 0 new entities...
Step  5 of 6: Find IDs of entities...
 [notice] Step  5 of 6: Find IDs of entities...
Step  6 of 6: Add field items to published entities...
 [notice] Step  6 of 6: Add field items to published entities...
  Checking for published items for the field: contact_description...
 [notice]   Checking for published items for the field: contact_description...
  Publishing 3 items for field: contact_description...
 [notice]   Publishing 3 items for field: contact_description...
-- PUBLISHING: 5|0 Array
(
    [record_id] => 1
)
SKIPPING: Not publishing 1|0 because the required property values are already published:Array
(
    [record_id] => 2
)
SKIPPING: Not publishing 2|0 because the required property values are already published:Array
(
    [record_id] => 3
)
  Checking for published items for the field: contact_name...
 [notice]   Checking for published items for the field: contact_name...
  Publishing 3 items for field: contact_name...
 [notice]   Publishing 3 items for field: contact_name...
-- PUBLISHING: 5|0 Array
(
    [record_id] => 1
)
SKIPPING: Not publishing 1|0 because the required property values are already published:Array
(
    [record_id] => 2
)
SKIPPING: Not publishing 2|0 because the required property values are already published:Array
(
    [record_id] => 3
)
  Checking for published items for the field: contact_project...
 [notice]   Checking for published items for the field: contact_project...
  Publishing 3 items for field: contact_project...
 [notice]   Publishing 3 items for field: contact_project...
SKIPPING: Not publishing 5|0 because the required property values are already published:Array
(
    [record_id] => 1
    [entity_id] => 
    [linker_id] => 
    [link] => 1
    [project_id] => 
)
SKIPPING: Not publishing 1|0 because the required property values are already published:Array
(
    [record_id] => 2
    [entity_id] => 
    [linker_id] => 
    [link] => 2
    [project_id] => 
)
SKIPPING: Not publishing 2|0 because the required property values are already published:Array
(
    [record_id] => 3
    [entity_id] => 
    [linker_id] => 
    [link] => 3
    [project_id] => 
)
  Checking for published items for the field: contact_type...
 [notice]   Checking for published items for the field: contact_type...
  Publishing 3 items for field: contact_type...
 [notice]   Publishing 3 items for field: contact_type...
-- PUBLISHING: 5|0 Array
(
    [record_id] => 1
)
SKIPPING: Not publishing 1|0 because the required property values are already published:Array
(
    [record_id] => 2
)
SKIPPING: Not publishing 2|0 because the required property values are already published:Array
(
    [record_id] => 3
)
Published 0 new entities, and 12 field values.
 [notice] Published 0 new entities, and 12 field values.
```

The code is marked up to print either "SKIPPING" or "PUBLISHING for every $matches entry. Since we are only seeing one such message per entity above despite entity 1 and 2 actually having two contact_project links each, we can conclude the other two entries are not in the matches array at all.

**Comment by laceysanderson** [comment] 2024-06-18 16:11
Fixed by merged PR 🎉

**Closed as completed by laceysanderson** 2024-06-18 16:11 UTC
Labels: bug - confirmed, Group 1 -  Tripal Content Types | Terms | Fields
