### ISSUE TITLE
Tripal Content - no records showing

### ISSUE THREAD

**Issue by martacsilva** [tripal/tripal#942] opened 2019-05-17 09:27 UTC
Hi!

My page for Tripal content is not working properly and I honestly can't figure out what's going on. When I filter my search for a specific type of content, it shows a "no content can be found" while also displaying the message "found X records". It's doing this for all types of content, as far as I can tell.
![Capture18](https://user-images.githubusercontent.com/47527249/57918213-35835780-788e-11e9-83c9-7042ad5914ad.PNG)

Did I accidentally click something I shouldn't have? This is happening only since yesterday I think.

Thanks in advance!

**Comment by martacsilva** [comment] 2019-05-17 09:50
Apparently it fixed itself!
Thank you.

**Comment by martacsilva** [comment] 2019-05-17 10:04
It might be a bug? Because it just happened again. As I'm filtering the results, at some point it stops showing the records. 
Apparently closing the tab and re-opening, fixes it.

**Comment by btski** [comment] 2019-06-24 16:04
Looks like you accidentally had it set to filter by type "Analysis". Hitting the reset button should have fixed your problem.

**Comment by martacsilva** [comment] 2019-06-24 16:07
But I only want to see Analysis, and I know I have 21 of them, as shown in the "Found 21 records".

**Comment by btski** [comment] 2019-06-24 21:56
Ah my mistake, should have read more carefully. I haven't been able to reproduce your problem.

**Comment by laceysanderson** [comment] 2019-06-25 15:24
Hmmm... I'm also unable to reproduce your problem. I tried filtering for different content types with reset in between about 10X and it worked every time. I'm marking this as a potential bug. If you could keep an eye on it trying to notice what might trigger it, that would be extremely helpful. In the meantime I guess the less satisfying fix is just to refresh the page when this happens.

**Comment by martacsilva** [comment] 2019-06-25 15:43
So I was able to reproduce it, but bear with me because this is a bit weird. I also don't remember if I did exactly this to trigger it the first time but oh well.

- In Tripal Content, select a Content Type ( in my case I've been using Analysis)
- After you filter it, SOMETIMES (I didn't get this if I had refreshed or reset the page previously) the option to choose a page number still appears at the top, even though the number of records is not enough for a second page
![Capture1](https://user-images.githubusercontent.com/47527249/60112612-081caa00-9768-11e9-83a2-b1f1413e1800.PNG)
- If you click one of those numbers it takes you to a page without any records (but the correct number still shows up at the top) and you don't have any numbers to go back to your "first page"
![Capture2](https://user-images.githubusercontent.com/47527249/60112711-313d3a80-9768-11e9-9f7b-0b36fcc502e1.PNG)

Hope that makes sense!

**Comment by laceysanderson** [comment] 2019-06-25 18:43
Oh, interesting! I added `?page=2` to the end of the URL when I knew there wasn't a second page and can reproduce: "no results" message when the page count says there are records:
<img width="837" alt="Screen Shot 2019-06-25 at 12 42 14 PM" src="https://user-images.githubusercontent.com/1566301/60124374-ae57b800-9746-11e9-9300-0358e03ac5ca.png">

I still didn't see the pager show up when there should only be one page but will look into that as a potential cause :-) Thanks for the update!

**Comment by spficklin** [comment] 2019-06-25 19:57
Hi @martacds are you using Tripal v2 or Tripal v3?

**Comment by spficklin** [comment] 2019-06-25 20:01
@all-contributors please add @btski for question

**Comment by martacsilva** [comment] 2019-06-26 09:39
> Hi @martacds are you using Tripal v2 or Tripal v3?

Hi @spficklin , I'm using Tripal v3

**Comment by laceysanderson** [comment] 2020-10-15 21:39
This is a weird side case potential bug which only affects Administrators in rare cases and can be fixed by reseting the filters on the page. As such, I'm marking it as "Please contribute".

**Comment by laceysanderson** [comment] 2022-12-07 03:14
Closing this as it won't be fixed in Tripal 3 and does not apply to Tripal 4.

**Closed as completed by laceysanderson** 2022-12-07 03:14 UTC
Labels: Community - Please Contribute, bug - potential
