### ISSUE TITLE
API function chado_db_select() uses up all database connection.

### ISSUE THREAD

**Issue by chunhuaicheng** [tripal/tripal#139] opened 2017-07-29 01:42 UTC
When calling chado_db_select() multiple times (such as in a loop), it uses up all available database connections and causes a blank page. This does not happen if one uses Drupal db_select() instead.

PDOException: SQLSTATE[08006] [7] FATAL: remaining connection slots are reserved for non-replication superuser connections in chado_db_select() (line 2017 of /local/sites/tripal3/sites/all/modules/tripal/tripal_chado/api/tripal_chado.query.api.inc).

**Comment by spficklin** [comment] 2018-05-25 21:45
@chunhuaicheng I remember we had a conversation about this in the recent past. Did you find a fix for it?  I cannot remember.

**Comment by chunhuaicheng** [comment] 2018-05-27 12:44
No. I don't have a fix. Users may avoid the issue by not using
chado_db_select() in a loop.


On May 25, 2018 2:45 PM, "Stephen Ficklin" <notifications@github.com> wrote:

@chunhuaicheng <https://github.com/chunhuaicheng> I remember we had a
conversation about this in the recent past. Did you find a fix for it? I
cannot remember.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tripal/tripal/issues/139#issuecomment-392195619>, or mute
the thread

**Comment by spficklin** [comment] 2018-06-16 07:29
I have submitted a PR #446 that resolves this issue.  @chunhuaicheng can you please review that PR?  The testing instructions are provided and if after you test it, just add the label 'Reviewer 1 Approved' and post a comment that it was successful. If not successful then of course post what went wrong.

Thanks.

**Comment by bradfordcondon** [comment] 2018-06-18 13:54
I merged but realized you specifically want @chunhuaicheng . I won't close the issue until hearing from him.

**Comment by spficklin** [comment] 2018-06-18 14:00
Oh, I requested @chunhuaicheng because he reported the error and I was trying to spread out reviewing so the load doesn't always fall on the same few folks.   But if the testing worked and the problem is fixed then I think we can close it out.

**Closed as completed by spficklin** 2018-06-18 14:00 UTC
Labels: bug - confirmed, Priority - Release Blocker, waiting on submitter
