### ISSUE TITLE
New API function tripal_add_user_file()

### ISSUE THREAD

**Issue by shawnawsu** [tripal/tripal#700] opened 2018-10-03 12:40 UTC
## Feature Request/Discussion

* This feature does not attempt to solve an existing problem with Tripal
* I am open to developing or collaborating on an extension module if this is not a good fit for Tripal Core

* This feature is Not Urgent

### Description

An API function that developers can use when they need to upload a file into a tripal user's folder (sites/default/files/tripal/users/#uid) for any reason. 

### Your Specific Use Case

The specific use case is for the tripal galaxy module for data file uploads for workflows when developers are using the tripal_galaxy api to run galaxy workflows outside the webform interface.

### Generally Applicable
This is generally applicable for any tripal site that needs to upload content into the specific tripal users folders.

**Comment by laceysanderson** [comment] 2019-10-26 04:12
Closing as a duplicate of #549

**Closed as completed by laceysanderson** 2019-10-26 04:12 UTC
