### ISSUE TITLE
GFF file upload keeps stalling at 37% of parsed lines

### ISSUE THREAD

**Issue by mdhar1980** [tripal/tripal#761] opened 2018-11-21 03:28 UTC
Hello!

I am attempting to upload a GFF file on Tripal 7.x-2.x (https://github.com/tripal/tripal.git). However, the job keeps stalling at around 37% of parsed lines.

There is no error output from the Drush command. The Tripal Jobs list just says, "Error." So I'm not sure how to troubleshoot.

I first increased the PHP memory_limit value, as advised in the tutorial, to 2048M. I then raised it to 5120M. Both times, the job stalled at about 37% (36.74% for the former, 37.71% for the latter). It seems like the difference should have been much different if that was the issue, but I don't know.

Please advise if you have any advice on how to move past this stalling, with no clear error message, of a GFF load.

Thank you!

**Comment by mdhar1980** [comment] 2018-11-21 06:06
Update: I then set memory_limit to 10240 (10x the tutorial's suggested) and the GFF load still stalled out at 37.88% of lines parsed.

**Comment by mdhar1980** [comment] 2018-11-21 18:51
With memory_limit set to -1 (or unlimited), the job still stalled at 37.19% of lines parsed.

The reason I thought memory_limit might be relevant is because, in a previous (non-production) attempt at loading Tripal, we'd adjusted that value to get past a stalling GFF load. It does not seem to be the issue this time.

**Comment by laceysanderson** [comment] 2018-11-21 19:55
I have never experienced this myself... Can you provide us with more information about the file? How many lines is it? and can you provide an excerpt or is it private? Have you confirmed that it's correct GFF3 format; maybe using an [online validator](http://genometools.org/cgi-bin/gff3validator.cgi)?

I notice you are using Tripal2... would it be possible to upgrade your site to Tripal3 legacy mode so that you can use the new Tripal3 GFF3 loader?

**Comment by mdhar1980** [comment] 2018-11-21 20:10
Hi, Lacey,

Thanks for the response. I've attached a sample from the file [UPDATE: To avoid the copy-paste issue, I've uploaded a new sample]. The whole file is 590,798 lines.

EDIT: Adding the version header was trivial, as I suspected. I was able to validate the entire GFF file (had to break it in two) and both halves were validated, with some warnings of this sort: 

> warning: seqid "chr15" on line 2 in file "/var/www/servers/genometools.org/htdocs/cgi-bin/gff3/ProdGFF_Half2.gff" has not been previously introduced with a "##sequence-region" line, create such a line automatically

NOTE: I was able to upload a smaller GFF taken off the head of the larger GFF file in question, and it loaded fine. So, I'm doubting the above ##sequence-region lines are the issue. Seems file size, and therefore maybe a memory setting, but I don't know what that might be.

We had stuck to Tripal v2, because we had previously gotten that to work (part of that process was figuring out the memory_limit problem), and needed to complete things quickly (not working right now, obviously). I'm not certain if I could upgrade, as my instructions are to use v2. If I could get this GFF to load that would be better.

Thanks for your help

[GFF_5lines.gff.txt](https://github.com/tripal/tripal/files/2606051/GFF_5lines.gff.txt)

**Comment by mdhar1980** [comment] 2018-11-21 20:19
Adding the version header, I get this from the validator: 

> line 3 in file "/var/www/servers/genometools.org/htdocs/cgi-bin/gff3/head-of-gff_11-21-18.txt" does not contain 9 tab (\t) separated fields

**Comment by mdhar1980** [comment] 2018-11-21 22:36
I tried uploading a smaller version (first five lines) and that finished fine.

(I deleted previous comments I made here about column number from the validator, as that was the result of a copy-and-paste. Will attempt validating again.)

**Comment by mdhar1980** [comment] 2018-11-21 23:06
I validated the sample I uploaded above, and it was validated (once I added the version line).

It did say the following:

>  seqid "000007F" on line 2 in file "/var/www/servers/genometools.org/htdocs/cgi-bin/gff3/GFF_5lines.gff.txt" has not been previously introduced with a "##sequence-region" line, create such a line automatically

**Comment by mdhar1980** [comment] 2018-11-22 14:16
I updated my response above to say that I validated the entire file (had to break it up in two due to size). Both halves were validated, with some warnings of this sort:

> warning: seqid "chr15" on line 2 in file "/var/www/servers/genometools.org/htdocs/cgi-bin/gff3/ProdGFF_Half2.gff" has not been previously introduced with a "##sequence-region" line, create such a line automatically

**Comment by mdhar1980** [comment] 2018-11-24 15:30
NOTE: I was able to upload a smaller GFF taken off the head of the larger GFF file in question, and it loaded fine. So, I'm doubting the above ##sequence-region lines are the issue. Seems file size, and therefore maybe a memory setting? But I don't know what that might be. Lacey, or others, are there any memory settings (in PostGRES, Drupal itself, PHP -- though we've adjusted several of those already) that you would suggest altering?

Thanks!

**Comment by laceysanderson** [comment] 2018-11-25 00:22
Since time is of the essence, I would be tempted to break your GFF3 file into 4 chunks and see if that works. That way you'll be able to move forward and we'll confirm there is nothing wrong with the file.

PS. I work on a breeder-focused portal and thus do not have any direct experience with the GFF3 loader -just trying to help as I can 😬

**Comment by laceysanderson** [comment] 2018-11-25 01:16
Oh, I meant to confirm that you do not need to add the `##sequence-region` lines to your GFF3 file. However, are you sure you've pre-loaded all the backbone sequences (those referenced in the first column)? Also, have you looked for errors in the apache error log (for me `/var/log/apache2/error.log`) or in the Drupal Watchdog log (Admin > Reports > Recent log messages)?

**Comment by mdhar1980** [comment] 2018-11-25 22:02
Hi, Lacey,

Thanks for your response. I attempted breaking up the file. The first quarter loaded fine. The second quarter stalled partway through the setting ranks of children stage. This is similar to what happened last time, before we had increased the PHP memory_limit setting (that is, both the whole GFF and later, smaller fractions would stall). So, I still suspect it's a memory setting somewhere. But I don't know what it might be... I'll look into the logs you mentioned later on.

Thanks

**Comment by bradfordcondon** [comment] 2018-11-26 01:12
do the third and fourth quarters load fine?  

Is it possible theres a circular relationship of some sort described in around the 37% (halfway through the second quarter?) mark thats short circuiting the loader?

**Comment by mdhar1980** [comment] 2018-11-27 00:36
Hi, Lacey,

I preloaded the Fasta file with the sequences (Pdac_Barhee_chr_unan_180126.all.maker.transcripts_HC.fasta). It has headers of this sort:

>Pdac_HC_000007FT0000100.1 000007F-augustus-gene-0.3-mRNA-1 transcript offset:52 AED:0.28 eAED:0.28 QI:52|0.63|0.83|0.91|0.54|0.5|12|348|475

I also preloaded the reference genome.

Regarding the error logs:

The Apache2 log has a bunch of entries for today of this sort: 

> '/var/www/tripal/web/help.php' not found or unable to stat." 

I'm not sure what that's related to or if it's relevant to the Chado loading, but I haven't attempted a load today. I will do so again and check that log.

The Drupal log error/warning messages all look to be of the following sort: 
	* Deprecated function: The each() function is deprecated. 
	* Warning: count(): Parameter must be an array or an object that implements Countable in theme_table() (line 2061 of /var/www/tripal/web/includes/theme.inc).
	* Error sending e-mail (from mid224@nyu.edu to mid224@nyu.edu).

Thanks,
Michael

**Comment by mdhar1980** [comment] 2018-11-27 00:42
Bradford,

I still need to prepare and try loading those. But I can say this: The entire GFF stalled at various numbers around 36-37% of the parsing-lines step. The second quarter stalled at about 10.19% of the next step, the Setting Children step. Then, I tried running the second quarter as ""Import only new features" (not import and update) and it stalled at around 90% of the Setting Children step. So, it doesn't seem to be a particular line that's causing problems, but I will try with the other quarters.

Thanks again

**Comment by mdhar1980** [comment] 2018-11-27 06:21
The third quarter of the GFF also stalled/quit (at about 99% of lines parsed). Output from the apache2 error logs looks similar as what I listed above, with a lot of lines like this (but with various specifics listed as not found):

script '/var/www/tripal/web/image.php' not found or unable to stat

**Comment by btski** [comment] 2019-03-30 13:56
@mdhar1980 I've had this problem with the tab delimited bulk loader. Tracking inserted records is hugely memory inefficient and will cause larger jobs to fail midway through. Perhaps that's your problem? Behavior is identical to what I have experienced. Here's my previous [post](https://github.com/tripal/tripal/issues/490).

**Comment by mdhar1980** [comment] 2019-04-21 15:28
@btski Thanks very much for commenting! I'm (belatedly) looking through your post. I'll see if there's any solution there that works for me. Alternatively, did you figure anything out that's not listed there?
Thanks!

**Comment by mpoelchau** [comment] 2019-04-23 03:48
@mdhar1980 in our case it helps if the gff3 file has ### directives between each gene model. (See https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md). You can add these directives using our program gff3_sort: https://github.com/NAL-i5K/GFF3toolkit

**Comment by laceysanderson** [comment] 2019-10-26 04:02
@mdhar1980 were you able to find a solution to your problem?

**Comment by mdhar1980** [comment] 2019-10-26 16:40
@laceysanderson No, at some point when I have more time for this issue, I'll come back to it. But in the meantime, we just sidestepped it to get most of the content we wanted up (e.g., setting up a JBrowse instance on our server and linking to it). So, it's not solved yet, but I plan on trying again at some point.

**Comment by laceysanderson** [comment] 2019-10-26 17:01
Thanks @mboudet for the update and sorry you haven't yet found a solution! We are unfortunately not able to support Tripal 2 as we've moved on to Tripal 4 development at this time... However, feel free to comment back here when you have time to work on this and we'll help you as we're able.

**Comment by mdhar1980** [comment] 2020-06-14 20:02
Hi, @laceysanderson -- Thanks again for your responses. I wanted to ask, as I had made note of your comment here about Tripal 4 development, if there was a timeline for that. I did find the development site for it (https://github.com/tripal/t4d8) but couldn't get an idea of timing. Is this something you know: when Tripal 4 is likely or planned to be released? Or any idea on how close that is? My lab PI was discussing Tripal 3 and wanted to know how close Tripal 4 was before transitioning to 3. Thanks!

**Comment by laceysanderson** [comment] 2020-06-14 22:47
Hi @mdhar1980, we're working on solidifying a timeline right now and will hopefully have a better idea in ~2 weeks. For now, we're hoping to have a full release of Tripal 4 by the end of this year. This is with the Drupal 7 end-of-life planned for Nov 2021 in mind as we know many will have extension modules and sites to upgrade and we want to provide as much time as possible for that.

**Comment by mdhar1980** [comment] 2020-06-14 23:43
OK, thanks!

**Comment by mdhar1980** [comment] 2020-06-30 22:42
Hi, again, @laceysanderson -- and thanks again for your responses. We finally have some time to go back to our Tripal issues and would like to upgrade to Tripal 3, ahead of the 4 debut. So, I just wanted to check on something you'd said before: "_would it be possible to upgrade your site to Tripal3 legacy mode?_" 
My question: Is an upgrade to "Tripal 3 legacy mode" a special sort of upgrade? I found this guide to upgrading from 2 to 3: https://tripal.readthedocs.io/en/latest/user_guide/install_tripal/upgrade_from_tripal2.html. Is that the appropriate one, or is there a different guide for doing it specifically in "legacy mode" as you described it? I'm thinking your "legacy" comment may refer to the "Enable Tripal v2 Legacy modules" statement in that linked guide? But not sure. Thank you!

**Comment by laceysanderson** [comment] 2020-07-01 00:23
Hi @mdhar1980, I'm happy to hear that -Tripal 3 really is a great version and the upgrade process should help with the eventual upgrade to Tripal 4.

> I notice you are using Tripal2... would it be possible to upgrade your site to Tripal3 legacy mode so that you can use the new Tripal3 GFF3 loader?

This entails a complete upgrade to Tripal 3 using the guide you linked to above. Usually the part of the Tripal 3 upgrade causing the most work is switching from using Tripal 2 custom templates to theme the content pages to Tripal Fields to provide specific pieces of content. My reference to Tripal3 legacy mode is referring to [Step 3: use legacy templates (optional)](https://tripal.readthedocs.io/en/latest/user_guide/install_tripal/upgrade_from_tripal2.html#step-3-use-legacy-templates-optional) which allows you to continue using your Tripal2 templates to theme the new content pages.It is not recommended but can be a way to ease the work of a Tripal 3 upgrade.

In your specific case, you will need to decide: how much time do you have to dedicate to an upgrade? how many customizations did you make to Tripal2 templates? If only custmization to labels and field position were done, you do not need legacy mode as that can be done through the UI in Tripal3.

**Comment by mdhar1980** [comment] 2020-07-03 22:30
Thanks! I notice that guide lists a command for downloading Tripal 3.1 (tripal-7.x-3.1), but I see that (at least) up through Tripal 3.3 is released (https://github.com/tripal/tripal/releases/tag/7.x-3.3). So, for the most up-to-date install, I'm assuming use tripal-7.x-3.3?

**Comment by mdhar1980** [comment] 2020-07-19 17:46
Hi, again, @laceysanderson -- I was able to make it much of the way through the guide for Tripal 3 update, but I'm stalled at the Prepare Chado step. I get a lot of errors of the type: 

```
WD tripal_chado: PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "tripal_custom_tables" does not exist                [error]
LINE 1: SELECT * FROM tripal_custom_tables WHERE table_name = 'conta...
                      ^: SELECT * FROM {tripal_custom_tables} WHERE table_name = :table_name; Array
```

Up until that point, I was able to get the other steps to work. However, I was not able to enable any modules using Drush. I had to use the Modules page on the website. With Drush, I would get errors like the following. I'm not sure if that's related:

```
DatabaseSchemaObjectExistsException: Table chado_bundle already exists. in DatabaseSchema->createTable() (line 663 of /var/www/html/includes/database/schema.inc).
Drush command terminated abnormally due to an unrecoverable error.  
```
and:

```
DatabaseSchemaObjectExistsException: Table redirect already exists. in DatabaseSchema->createTable() (line 663 of /var/www/html/includes/database/schema.inc).
Drush command terminated abnormally due to an unrecoverable error. 
```

Thanks for any insight.

--Michael

**Comment by mdhar1980** [comment] 2020-07-20 22:38
Since this is a pretty different issue from the original one in this thread, I've created a new thread here. Feel free to respond either place: https://github.com/tripal/tripal/issues/1072

**Comment by spficklin** [comment] 2020-09-20 09:59
I think this issue can be closed as it sounds like @mdhar1980 has begun upgrade to Tripal v3 and has hit on other issues.  So the hangup on the GFF3 loader with Tripal v2 may not be a problem we need to fix.   We are completely rewriting the GFF3 importer for Tripal v3 and the issue related to that is here: https://github.com/tripal/tripal/issues/1040.   

If I'm wrong and this issue needs to stay open please comment and we can reopen it.

**Closed as completed by spficklin** 2020-09-20 09:59 UTC
Labels: Community - Question, waiting on submitter

**Comment by mdhar1980** [comment] 2020-10-06 02:13
Yes, than you for updating. We've now updated to Tripal 3 and will be attempting to get everything working with that version. Thanks!

**Comment by mdhar1980** [comment] 2020-12-11 17:16
Just wanted to update this that we did in fact (a while ago) upgrade to Tripal 3, and the GFF loaded just fine with that version. Thanks!

**Comment by spficklin** [comment] 2020-12-11 18:18
Thanks for the update @mdhar1980 !
