### ISSUE TITLE
Tripal2 gff3 loader won't load all Ontology_term values

### ISSUE THREAD

**Issue by mpoelchau** [tripal/tripal#926] opened 2019-04-24 19:47 UTC
### System information

* Tripal Version: 2
* Drupal Version: 7.64
* PostgreSQL Version: 9.6.12
* PHP Version: 7.1.28

### Issue description

I've started loading KEGG, InterPro and GO annotations via the Tripal gff3 loader, using the reserved gff3 attribute Ontology_term, based this discussion: https://github.com/GMOD/Chado/issues/74. Previously we've loaded these using the Dbxref attribute.

I was unable to find and therefore load an InterPro obo file prior to the gff3 load. Tripal gave me a number of warnings about this. 

It turns out that Tripal would also not load any values under the Ontology_term attribute that occurred _after_ the InterPro entries. So, in this example: 
`Ontology_term=KEGG:K11978,InterPro:IPR003126,GO:0004842,GO:0008270,InterPro:IPR013993;`
Only KEGG:K11978 is associated with the feature after the gff3 load, but not GO:0004842 and GO:0008270. 

If I move the values around, so that the 2 GO terms occur _before_ the InterPro terms, then they load. 

It would be nice if Tripal could at least throw a warning that all subsequent ontology terms will also not be loaded; better yet if it would process them, though.

#### Steps to reproduce

Here's a gff3 snippet to work with: 
```
QKKF02000028.1  Genbank gene    3267    4896    .       +       .       end_range=4896,.;gbkey=Gene;gene_biotype=protein_coding;locus_tag=LSTR_LSTR016833;partial=true;ID=LSTR016833;Name=evm.model.Contig22443.1;Alias=gene-LSTR_LSTR016833,evm.TU.Contig22443.1;
QKKF02000028.1  Genbank mRNA    3267    4896    .       +       .       locus_tag=LSTR_LSTR016833;ID=LSTR016833-RA;Parent=LSTR016833;Ontology_term=KEGG:K05096,InterPro:IPR002290,InterPro:IPR020635,GO:0004672,GO:0004713,InterPro:IPR001245,GO:0006468,InterPro:IPR000719,GO:0005524;
QKKF02000028.1  Genbank exon    3267    3293    .       +       .       gbkey=mRNA;inference=similar to AA sequence:INSD:KDR14705.1;locus_tag=LSTR_LSTR016833;orig_protein_id=gnl|WGS:QKKF|LSTR016833-RA-polypeptide001;orig_transcript_id=gnl|WGS:QKKF|LSTR016833-RA;partial=true;product=hypothetical protein;Alias=exon-gnl|WGS:QKKF|LSTR016833-RA-1;ID=LSTR016833-RA-exon001;Parent=LSTR016833-RA;
QKKF02000028.1  Genbank exon    3986    4896    .       +       .       end_range=4896,.;gbkey=mRNA;inference=similar to AA sequence:INSD:KDR14705.1;locus_tag=LSTR_LSTR016833;orig_protein_id=gnl|WGS:QKKF|LSTR016833-RA-polypeptide001;orig_transcript_id=gnl|WGS:QKKF|LSTR016833-RA;partial=true;product=hypothetical protein;Alias=exon-gnl|WGS:QKKF|LSTR016833-RA-2;ID=LSTR016833-RA-exon002;Parent=LSTR016833-RA;
QKKF02000028.1  Genbank CDS     4027    4896    .       +       0       Dbxref=NCBI_GP:RZF49331.1;Name=RZF49331.1;end_range=4896,.;gbkey=CDS;locus_tag=LSTR_LSTR016833;orig_transcript_id=gnl|WGS:QKKF|LSTR016833-RA;partial=true;product=hypothetical protein;protein_id=RZF49331.1;Alias=cds-RZF49331.1;ID=LSTR016833-RA-CDS;Parent=LSTR016833-RA;
QKKF02000028.1  Genbank polypeptide     4027    4896    .       +       .       ID=LSTR016833-PA;Parent=LSTR016833-RA;Dbxref=NCBI_GP:RZF49331.1;end_range=4896,.;locus_tag=LSTR_LSTR016833;orig_transcript_id=gnl|WGS:QKKF|LSTR016833-RA;partial=true;product=hypothetical protein;protein_id=RZF49331.1;Alias=cds-RZF49331.1;
```

#### Error messages and screenshots
Here's what I get when I load the above gff: 
```
SELECT feature.uniquename, cvterm.name, cvterm.definition, cvterm.cv_id, dbxref.accession, dbxref.db_id FROM "feature" inner join feature_cvterm ON ( feature.feature_id = feature_cvterm.feature_id ) inner join cvterm ON (feature_cvterm.cvterm_id = cvterm.cvterm_id) inner join dbxref ON ( cvterm.dbxref_id = dbxref.dbxref_id ) where feature.uniquename='LSTR016833-RA';

LSTR016833-RA	FLT1, VEGFR1 (K05096)	FMS-like tyrosine kinase 1	41	K05096	61
```
I've confirmed that the GO terms that aren't associated with the feature are in the database, for example: 

```
SELECT dbxref.accession, db.name FROM "dbxref" inner join db ON ( dbxref.db_id = db.db_id ) where dbxref.accession ='0004672';

0004672	GO
```

On a related note - does anyone know of an InterPro .obo file to use with Tripal? 

Thanks!

Monica

**Comment by spficklin** [comment] 2019-04-24 19:52
Thanks for reporting this issue @mpoelchau.
> It would be nice if Tripal could at least throw a warning that all subsequent ontology terms will also not be loaded; better yet if it would process them, though.

I think it should work correctly :-)  As in all terms being loaded.  

Just curious how did you get InterPro and KEGG terms to load as there are no official OBOs for those and @bradfordcondon and I have had some discussions about how to get the KEGG vocabulary properly represented in Chado and there are some issues with it.  Did you load them without the ontology hierarchy?

**Comment by mpoelchau** [comment] 2019-04-24 20:00
I didn't get InterPro to load, since I couldn't find an obo file. 

For Kegg I used this: https://github.com/tripal/tripal_analysis_kegg/blob/7.x-3.x/kegg.obo

**Comment by spficklin** [comment] 2019-04-24 20:26
Okay, I think we can fix this easy enough.  I suspect it gave up once it hit that first IPR term that couldn't be loaded but it should continue with all of them.

**Comment by mpoelchau** [comment] 2019-04-24 20:32
Awesome, thanks!

**Comment by spficklin** [comment] 2019-04-25 00:17
@mpoelchau . The GFF loader is not importing attributes not in the GFF3 spec (e.g. locus_tag, gene_biotype, end_range, etc...).  Were you hoping those would be imported as well?

**Comment by spficklin** [comment] 2019-04-25 01:11
Whoops. It did import the attributes. I forgot to attach any newly added properties to the content types which is why I thought it hadn't happened. But it did. So, that is good. 

I did fix the bug with not loading the ontologies terms.  Can you checkout this branch and re-run your GFF import and see if the problem is fixed: `926-tv3-GFF_ontology_import`

**Comment by mpoelchau** [comment] 2019-04-25 14:10
@spficklin thanks for the fix! Unfortunately I can't test now since 1) our main site (where I originally found the bug) is still on Tripal v2; and 2) we have a tripal3 testing site, but I managed to screw something up so the gff3 won't import and probably won't get around to fixing it for another 2-3 weeks. Apologies...

**Comment by spficklin** [comment] 2019-04-25 15:03
Okay. no worries. I'm going to issue a pull request for this to get it into the core code then. I ran the exact GFF snippet that you posted above and all of the GO terms went in as expected. I don't have KEGG or Interpro loaded so those didn't get imported.

**Comment by spficklin** [comment] 2019-05-14 21:23
Fix has been pushed. @mpoelchau let us know if you have problems on your Tv3 sites.

**Closed as completed by spficklin** 2019-05-14 21:23 UTC
Labels: bug - confirmed
