### ISSUE TITLE
Searching views does not always work

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#233] opened 2017-12-18 10:28 UTC
Hi Stephen, so I upgraded to the latest development version + patched drupal + patched views

Cannot search the name field by creating a filter in views. Not sure if anyone else is experiencing search issues that could shed some light on why this is happening?

**Comment by spficklin** [comment] 2017-12-18 16:50
@risharde can you provide more details about what you tried and what behavior you were expecting?  What content type are you trying to use with views?

**Comment by risharde** [comment] 2017-12-18 17:01
Thanks for your response Stephen! Tripal Content Type 'Contact'
In particular, when trying to Add a filter in Views by Contact Name and making this filter exposed for users to choose how they want to search Contact Name, it doesn't seem to work - no records are returned. I'll send you a link via Slack so you can perhaps see the issue since I'm unable to describe it any better.

**Comment by spficklin** [comment] 2017-12-18 17:09
Okay. we may have a bug here.... can you try a search with instead of "Contains" as the operation to "is equal to" and enter the full contact name?

**Comment by risharde** [comment] 2017-12-18 17:11
Is equal to seems to work
Starts with and contains don't seem to work

Length is shorter than gives the following error as well
Error: Call to undefined method tripal_views_query::placeholder() in views_handler->placeholder() (line 604 of /var/www/Drupal/sites/all/modules/views/includes/handlers.inc).

**Comment by spficklin** [comment] 2017-12-18 17:12
Okay, we have a bug then that we have to fix.... We'll let you know when it's resolved in the development branch.

**Comment by risharde** [comment] 2017-12-18 17:13
Thanks Stephen!

**Comment by laceysanderson** [comment] 2018-05-30 23:04
This should be fixed in the most recent dev (was fixed in #382). Can you confirm it's fixed for you @risharde ?

**Comment by laceysanderson** [comment] 2018-07-19 18:56
Considering no news, good news... Since this is confirmed fixed by multiple users I'm going to close the issue. However, @risharde is you are still experiencing this please re-open and let us know :-)

**Closed as completed by laceysanderson** 2018-07-19 18:56 UTC
Labels: bug - confirmed, waiting on submitter
