### ISSUE TITLE
Annotations pane hidden when empty field is added

### ISSUE THREAD

**Issue by jwest60** [tripal/tripal#992] opened 2019-09-04 14:54 UTC
### System information

* Tripal Version: 7.x-3.1
* Drupal Version: 7.61
* PostgreSQL Version: 10.5
* PHP Version: 7.1.20

### Issue description

Under **Admin->Structure->Tripal Content Types->mRNA** there is a field called Annotations that appears under a pane called Annotations. When an empty field is added under this pane and is structured before the Annotations field, the entire pane will not display. The expected behavior would be to have the empty field not display while the Annotations field would still appear. See screenshot below for an example of the structure.

#### Steps to reproduce

1. Find any mRNA page on your site that contains annotations and confirm that the Annotations pane is displaying properly.
2. Navigate to **Admin->Structure->Tripal Content Types->mRNA**.
3. Locate the Annotations pane and find the Annotations field underneath it.
4. Choose any empty field (I used the Is Obsolete field from the Summary pane, see screenshot) and structure it so that it appears underneath the Annotations pane and before the Annotations field.
5. Return to the mRNA page and confirm that the Annotations page is no longer being displayed.

#### Error messages and screenshots

![image](https://user-images.githubusercontent.com/32902460/64266093-00b11400-cf02-11e9-8b22-b1384d2e6872.png)

**Comment by laceysanderson** [comment] 2019-10-27 20:26
Hi @jwest60, Thank you for reporting this. The problem is a bit more complicated then it at first seems.

 **Set the content type is set to "hide empty fields"**

When the cache is cleared or the first time the page loads, the pane is missing is if contains any empty fields. 
![firstpageload](https://user-images.githubusercontent.com/1566301/67641127-559b5600-f8c5-11e9-8350-57ae3432640f.png)

However, on the second page load, the pane will be present as expected.
![secondpageload](https://user-images.githubusercontent.com/1566301/67641129-58964680-f8c5-11e9-9b29-c3a7254188b8.png)

**This occurs on any content type, in any pane regardless of whether "load with ajax" is set or not.**

@almasaeed2010 do you have any idea as to why this may be occurring? I thought we experienced this at one point but had fixed it.

**Comment by laceysanderson** [comment] 2019-11-11 20:24
@almasaeed2010 do you have time to take a look at this?

**Comment by almasaeed2010** [comment] 2019-11-12 18:51
Hello @laceysanderson 

Sorry I haven't noticed that I was tagged previously!

I spent all morning looking at this but couldn't really figure out what's happening. The issue is very strange since the code that checks whether a field should be attached is the same regardless of whether the entity is cached. There is probably something in the lifecycle of the entity that I am missing. Because there are many `_alter()` hooks that could affect this behavior, it's really difficult to trace the code 😞

**Comment by spficklin** [comment] 2021-03-12 19:32
It has been quite a while since anyone commented on this issue. I'm going to close it out, but please comment if it needs to be reopened.

**Closed as completed by spficklin** 2021-03-12 19:32 UTC
Labels: bug - confirmed
