### ISSUE TITLE
Error during EDAM vocabulary loading

### ISSUE THREAD

**Issue by shmenolin** [tripal/tripal#1156] opened 2021-01-18 20:14 UTC
I am trying to load EDAM vocabulary to the Tripal. However, I got the following error. What could be the reason for this?
```
Running 'OBO Vocabulary Loader' importer
NOTE: Loading of file is performed using a database transaction. 
If it fails or is terminated prematurely then all insertions and 
updates are rolled back and will not be found in the database

Downloading URL http://edamontology.org/EDAM.obo, saving to /private/var/folders/ft/1drrm69j74728knx0jbh9h6c0000gn/T/obo_XkZNcQ
Step 1: Preloading File /private/var/folders/ft/1drrm69j74728knx0jbh9h6c0000gn/T/obo_XkZNcQ...
array_key_exists() expects parameter 2 to be array, null given OBOImporter.inc:919                                                                                                               [warning]
array_key_exists() expects parameter 2 to be array, null given OBOImporter.inc:925                                                                                                               [warning]
Cannot cache terms without a default CV.Array
(
    [id] => Array
        (
            [0] => EDAM_data:0005
        )

    [name] => Array
        (
            [0] => Resource type
        )

    [subset] => Array
        (
            [0] => bioinformatics
            [1] => data
            [2] => edam
        )

    [created_in] => Array
        (
            [0] => "beta12orEarlier"
        )

    [def] => Array
        (
            [0] => "A type of computational resource used in bioinformatics." [http://edamontology.org]
        )

    [namespace] => Array
        (
            [0] => data
        )

    [obsolete_since] => Array
        (
            [0] => "beta12orEarlier"
        )

    [] => Array
        (
            [0] => 
        )

    [is_obsolete] => Array
        (
            [0] => true
        )

)

[site http://default] [TRIPAL ERROR] [TRIPAL_JOB] Cannot cache terms without a default CV.Array(    [id] => Array        (            [0] => EDAM_data:0005        )    [name] => Array        (            [0] => Resource type        )    [subset] => Array        (            [0] => bioinformatics            [1] => data            [2] => edam        )    [created_in] => Array        (            [0] => "beta12orEarlier"        )    [def] => Array        (            [0] => "A type of computational resource used in bioinformatics." [http://edamontology.org]        )    [namespace] => Array        (            [0] => data        )    [obsolete_since] => Array        (            [0] => "beta12orEarlier"        )    [] => Array        (            [0] =>         )    [is_obsolete] => Array        (            [0] => true        ))

```

* Tripal Version: 7.x-3.4
* Drupal Version: 7.77
* PostgreSQL Version: 12.3
* PHP Version: 7.3.11

**Comment by spficklin** [comment] 2021-01-19 16:07
Hi @shmenolin Thanks for reporting this. I'll take a look into it and get back to you once I figure out what's going on.

**Comment by spficklin** [comment] 2021-03-06 01:55
Hi @shmenolin I just recently was able to load the EDAM vocabulary with the most recent development version of Tripal. There is a bug in the v3.5 version that we just discovered that prevents this and a fix was just merged in.  If you are able, can you use the development branch of Tripal and see if you can load EDAM?

**Comment by spficklin** [comment] 2021-03-12 19:16
Hey @shmenolin sorry to be a nag on this issue.  If this is a problem we'd like to makes sure it gets fixed before we release Tripal v3.6.  Any chance you were able to check to see if the issue is resolved for you?  We aren't able to reproduce the problem so I wanted to see if you still have the issue.

**Comment by shmenolin** [comment] 2021-03-24 21:43
Sorry for the late response. But yes it still exists.

**Comment by laceysanderson** [comment] 2022-12-07 03:12
Closing as the submitted did not reply.

**Closed as completed by laceysanderson** 2022-12-07 03:12 UTC
Labels: bug - confirmed, waiting on submitter
