### ISSUE TITLE
throw an Error when load the obo file for gene_ontology

### ISSUE THREAD

**Issue by a2htray** [tripal/tripal#186] opened 2017-11-08 07:01 UTC
current environment

1. postgresql9.5
2. drupal-7.56
3. tripal 2
4. chado 1.3

`WD tripal_cv: Could not fill cvtermpath table: SQLSTATE[54001]: Statement too complex: 7 ERROR:  stack depth limit exceeded                                                   [error]`

**Comment by a2htray** [comment] 2017-11-08 07:02
some one says it is an issue of postgresql, any way to resolve it?

**Comment by shawnawsu** [comment] 2017-11-14 19:48
Hi @a2htray, 

We are actively working on this. The root of the problem is a self referential relationship in the gene ontology. We are hoping to have a fix soon and will let you know as soon as it's ready, hopefully by the end of the week.

Thank you for your patience!
Shawna

**Comment by shawnawsu** [comment] 2017-12-12 12:59
Hi @a2htray ,

There is now a fix for this issue available in the current 7.x-3.x branch. 

Thanks!
Shawna

**Comment by a2htray** [comment] 2018-01-03 14:19
thanks for resolving, but i need it working with the chado_search that it is not compatible with 3.x

**Comment by a2htray** [comment] 2018-01-08 02:36
@shawnawsu ，i had try to using the 7.x-3x branch, also had the same problem

**Comment by spficklin** [comment] 2018-01-08 17:29
HI @a2htray.   I'm not sure I understand what you mean when you say you need it to work with chado_search?  Do you mean you need the fix ported to Tripal v2.x as well?

**Comment by a2htray** [comment] 2018-01-19 03:08
Hi, @spficklin ,yes, i hope it works well via Tripal v2.x.

**Comment by spficklin** [comment] 2018-03-24 01:53
This should be fixed in the current 7.x-3.x branch with the pull request from @shawnawsu .  Please comment if there continue to be issues.

**Comment by zhuyiqin** [comment] 2018-04-13 01:05
hi, I'm currently working on the 2.x branch and met the same issue when loading the Gene Ontology obo file. Is there any way to deal with it now, or do I have to upgrade to the 3.x branch? Thanks.

**Comment by spficklin** [comment] 2018-05-05 06:32
Sorry @zhuyiqin for the slow reply.  We will be including the fixes for the GO loading on the 2.x branch.  I'm reopening to remind us to do that.

**Comment by laceysanderson** [comment] 2019-03-20 03:39
Unfortunately there is not the developer hours to backport this to Tripal2. Please upgrade to Tripal 3, using legacy-mode if needed.

**Closed as completed by laceysanderson** 2019-03-20 03:39 UTC
