### ISSUE TITLE
Bug in API function 'chado_generate_var' causes a blank page

### ISSUE THREAD

**Issue by chunhuaicheng** [tripal/tripal#333] opened 2018-04-11 21:55 UTC
### System information
* Tripal Version: 7.x-2.x
* Drupal Version: 7.56
* PostgreSQL Version: 9.4
* PHP Version: 7.0.28

### Issue description
Bug in API function 'chado_generate_var' causes a blank page. When displaying cvterms that have backslash '\\' in its definition, in this case: the 'cell death' cvterm, on a feature page through the template 'tripal_feature_terms.tpl.php', the site will break. 

The error message:

ParseError: syntax error, unexpected 'apoptotic' (T_STRING), expecting ',' or ')' in php_eval() (line 1 of /local/sites/test.cottongen.org/drupal-7.41/modules/php/php.module(80) : eval()'d code).

**Comment by laceysanderson** [comment] 2018-04-13 16:22
I don't have the term 'cell death' in my site. Which ontology is it from and what is the description which causes the error?

**Comment by chunhuaicheng** [comment] 2018-04-13 16:29
It is from the Gene Ontology's 'biological_process'. Its definition reads:
Any biological process that results in permanent cessation of all vital functions of a cell. A cell should be considered dead when any one of the following molecular or morphological criteria is met: (1) the cell has lost the integrity of its plasma membrane; (2) the cell, including its nucleus, has undergone complete fragmentation into discrete bodies (frequently referred to as \\"apoptotic bodies\\"); and/or (3) its corpse (or its fragments) have been engulfed by an adjacent cell in vivo. [GOC:mah, GOC:mtg_apoptosis]

**Comment by bradfordcondon** [comment] 2018-04-13 16:47
Hi all: If it helps with testing, this term is included in the [plant GOslim](http://www.geneontology.org/ontology/subsets/goslim_plant.obo), which loads in ~2 minutes as opposed to the full GO which takes a very long time on my dev instance.

**Comment by chunhuaicheng** [comment] 2018-04-13 16:55
Thanks Bradford. Could yo check if your 'cell death' definition has backslash '\\' in it? I wonder if it's just me. I think I loaded GO with Tripal OBO loader and 'cell death' is not the only one with backslash in it.

**Comment by bradfordcondon** [comment] 2018-04-13 16:56
>Any biological process that results in permanent cessation of all vital functions of a cell. A cell should be considered dead when any one of the following molecular or morphological criteria is met: (1) the cell has lost the integrity of its plasma membrane; (2) the cell, including its nucleus, has undergone complete fragmentation into discrete bodies (frequently referred to as apoptotic bodies). The cell corpse (or its fragments) may be engulfed by an adjacent cell in vivo, but engulfment of whole cells should not be considered a strict criteria to define cell death as, under some circumstances, live engulfed cells can be released from phagosomes (see PMID:18045538). [GOC:mah, GOC:mtg_apoptosis, PMID:25236395]

checked teh DB, no escapes there either.

**Comment by bradfordcondon** [comment] 2018-04-13 16:58
Unfortunately I can't cross check against our dev site: it didnt use the OBO loader at all.

**Comment by chunhuaicheng** [comment] 2018-04-13 17:04
Okay. I think I'll manually remove those back slashes in the DB to avoid the bug for now. I thought I shouldn't do that but you confirmed the backslash shouldn't be there in the first place. Thanks for checking.

**Comment by laceysanderson** [comment] 2018-04-13 17:22
Interestingly it looks like the definitions are slightly different: @bradfordcondon doesn't have `(3)  its corpse (or its fragments) ...`. This implies someone should try to reload the full GO to see if the newest version contains the backslash or not.

**Comment by bradfordcondon** [comment] 2018-04-13 17:26
The mini GO set is purposefully missing terms and relationships.

You can just look at the full OBO http://purl.obolibrary.org/obo/go.obo .

**Comment by laceysanderson** [comment] 2018-04-13 18:41
*slaps forehead* good point about just checking the file.

> [Term]
> id: GO:0008219
> name: cell death
> namespace: biological_process
> def: "Any biological process that results in permanent cessation of all vital functions of a cell. A cell should be considered dead when any one of the following molecular or morphological criteria is met: (1) the cell has lost the integrity of its plasma membrane; (2) the cell, including its nucleus, has undergone complete fragmentation into discrete bodies (frequently referred to as apoptotic bodies). The cell corpse (or its fragments) may be engulfed by an adjacent cell in vivo, but engulfment of whole cells should not be considered a strict criteria to define cell death as, under some circumstances, live engulfed cells can be released from phagosomes (see PMID:18045538)." [GOC:mah, GOC:mtg_apoptosis, PMID:25236395]
> comment: This term should not be used for direct annotation. The only exception should be when experimental data (e.g., staining with trypan blue or propidium iodide) show that cell death has occurred, but fail to provide details on death modality (accidental versus programmed). When information is provided on the cell death mechanism, annotations should be made to the appropriate descendant of 'cell death' (such as, but not limited to, GO:0097300 'programmed necrotic cell death' or GO:0006915 'apoptotic process'). Also, if experimental data suggest that a gene product influences cell death indirectly, rather than being involved in the death process directly, consider annotating to a 'regulation' term.
> subset: goslim_agr
> subset: goslim_chembl
> subset: goslim_generic
> subset: goslim_mouse
> subset: goslim_plant
> subset: gosubset_prok
> synonym: "accidental cell death" RELATED []
> synonym: "necrosis" RELATED []
> is_a: GO:0009987 ! cellular process

Confirmed that neither the quotes or backslash are supposed to be there in the most recent version of GO.

**Comment by laceysanderson** [comment] 2018-05-30 23:00
Closing this since it's not a problem with the current version of any known ontologies...

**Closed as completed by laceysanderson** 2018-05-30 23:00 UTC
Labels: bug - confirmed
