### ISSUE TITLE
PDO Error on mRNA: negative substring length not allowed

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#706] opened 2018-10-03 17:42 UTC
### System information

* Tripal Version: 7.x-3.x
* Drupal Version: 7.x
* PostgreSQL Version: 9.4
* PHP Version: 5.6

### Issue description
I just sync'd some mRNA pages and when I try to view one of them I get the following PDO error:
![screen shot 2018-10-03 at 11 25 34 am](https://user-images.githubusercontent.com/1566301/46427612-13720600-c6ff-11e8-8784-812ecbb9e0d8.png)

It appears to be happening on this query: https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/api/modules/tripal_chado.feature.api.inc#L244-L308

#### Steps to reproduce
1. Load the data from Tripal DevSeed.
2. Publish the mRNA content type (should be 200 records).
3. Go to TripalContent, and select `FRAEX38873_v2_000001700.1` (I saw this problem a large number of them).
4. Enjoy a PDO error taking over your whole page 😝 

#### Error messages and screenshots
Error message included in text below for ease:
> PDOException: SQLSTATE[22011]: Substring error: 7 ERROR: negative substring length not allowed: SELECT featureloc_id, srcname, srcfeature_id, strand, srctypename, typename, fmin, fmax, upstream, downstream, adjfmin, adjfmax, substring(residues from (cast(adjfmin as int4) + 1) for cast((upstream + (fmax - fmin) + downstream) as int4)) as residues, genus, species FROM ( SELECT FL.featureloc_id, OF.name srcname, FL.srcfeature_id, FL.strand, OCVT.name as srctypename, SCVT.name as typename, FL.fmin, FL.fmax, OO.genus, OO.species, CASE WHEN FL.strand >= 0 THEN CASE WHEN FL.fmin - :upstream <= 0 THEN 0 ELSE FL.fmin - :upstream END WHEN FL.strand < 0 THEN CASE WHEN FL.fmin - :downstream <= 0 THEN 0 ELSE FL.fmin - :downstream END END as adjfmin, CASE WHEN FL.strand >= 0 THEN CASE WHEN FL.fmax + :downstream > OF.seqlen THEN OF.seqlen ELSE FL.fmax + :downstream END WHEN FL.strand < 0 THEN CASE WHEN FL.fmax + :upstream > OF.seqlen THEN OF.seqlen ELSE FL.fmax + :upstream END END as adjfmax, CASE WHEN FL.strand >= 0 THEN CASE WHEN FL.fmin - :upstream <= 0 THEN FL.fmin ELSE :upstream END ELSE CASE WHEN FL.fmax + :upstream > OF.seqlen THEN OF.seqlen - FL.fmax ELSE :upstream END END as upstream, CASE WHEN FL.strand >= 0 THEN CASE WHEN FL.fmax + :downstream > OF.seqlen THEN OF.seqlen - FL.fmax ELSE :downstream END ELSE CASE WHEN FL.fmin - :downstream <= 0 THEN FL.fmin ELSE :downstream END END as downstream, OF.residues FROM chado.featureloc FL INNER JOIN chado.feature SF on FL.feature_id = SF.feature_id INNER JOIN chado.cvterm SCVT on SF.type_id = SCVT.cvterm_id INNER JOIN chado.feature OF on FL.srcfeature_id = OF.feature_id INNER JOIN chado.cvterm OCVT on OF.type_id = OCVT.cvterm_id INNER JOIN chado.organism OO on OF.organism_id = OO.organism_id WHERE SF.feature_id = :feature_id and NOT (OF.residues = '' or OF.residues IS NULL) ORDER BY fmin) as tbl1 ; Array ( [:upstream] => 0 [:downstream] => 0 [:feature_id] => 2654 ) in chado_query() (line 1704 of /var/www/dev/tripal/sites/all/modules/tripal/tripal_chado/api/tripal_chado.query.api.inc).
```

**Comment by bradfordcondon** [comment] 2018-10-04 15:37
I've seen this before as well. https://github.com/statonlab/tripal_dev_seed/issues/66

Is it possible the problem is with devseed?  ie the GFF file perhaps?

**Comment by bradfordcondon** [comment] 2019-01-03 15:11
A rough fix for this issue is to  enable **Load field using AJAX** in the bundle settings (structure -> tripal content types -> (mrna, or whatever feature type is giving you this error) -> edit

The PDO error occurs, but it no longer breaks the site.


as for WHY the problem occurs... Im not sure.  the SQL itself looks OK (albeit very complex.  is it a good idea to have so much logic packed into the SQL?  I know its faster but it makes it much harder to troubleshoot)

https://github.com/tripal/tripal/blob/02e63a9f531a271e83545878183c9f9f5fe91d27/tripal_chado/api/modules/tripal_chado.feature.api.inc#L243-L334



theres a lot more going on here that confuses me though.  For example, it appears that we get the sequence from the parent, even if the feature itself has a residues value.  Why derive from the parent in this case?


easiest solution is that the devseed GFF file is wrong, so lets fix that first.


edit: pretty confident i got it.  genes are double-defined for some of the features in the GFF.  deleting duplicates should resolve.

**Comment by bradfordcondon** [comment] 2019-01-03 18:37
hi @laceysanderson if you rerun devseed this should be resolved.   

You can confirm by `select residues from chado.feature where name='Contig10011'; ` and verifying it isnt a string of a bunch of fasta header tags.

See https://github.com/statonlab/tripal_dev_seed/issues/73

That said, in other contexts, this error will still occur when the featureloc coordinates exceed the bounds of the actual feature length.  Maybe thats not something we need to worry about because it means that the FASTA file sequences or GFF file or both are corrupt in some way. 

With that in mind should we resolve this issue or keep open?

**Comment by laceysanderson** [comment] 2019-01-03 18:51
That's a hard call. Ideally in this case we would have a Tripal error rather then a PDO error but I'm not sure it's worth the time added by an extra query to check first... It could go either way -what are your thoughts?

PS. I'm glad to hear it's fixed in DevSeed!

**Comment by bradfordcondon** [comment] 2019-01-03 18:57
I agree throwing a tripal error first would be ideal.

the problem is i'd have to understand that SQL statement to know what to check for to ensure we dont end up with a negative substring, and i already sank more time in it than its worth.

With that in mind I guess i move to tag as wontfix and note that this error occurs when the parent residues wont support whats specified in featureloc. 

If I did have to try and fix it I would check the max value of featureloc and ensure it isnt bigger than the parent feature's length(residues).  BUT I'd want to do that without breaking my hacky solution in devseed (where the parent feature has no resideus, because the whole point is to keep it small, i dont want to load full scaffolds into the database).  Not to mention that might not be sufficient to cover all cases when its a problem because theres so many logic switches in the SQL the query that goes into the substring ....

**Comment by spficklin** [comment] 2019-04-23 22:12
Since this is not urgent and we don't have resources to dig into it. I'm marking it as maybe later.

**Closed as completed by spficklin** 2019-04-23 22:12 UTC
Labels: bug - potential
