### ISSUE TITLE
Regular updating chado materialized views

### ISSUE THREAD

**Issue by taytayp** [tripal/tripal#353] opened 2018-04-26 20:51 UTC
As a suggestion, it would be great if the materialized views in `tripal/storage/chado/mviews` could be updated automatically and regularly, so that the materialized view would be up to date with any additional elements added to the database.

**Comment by laceysanderson** [comment] 2018-04-26 20:58
Good suggestion :-) I think we would want to do so via the Drupal Cron. We would definitely need to add configuration for this since not all sites need an automatic update (e.g. sites with static data would not want to re-generate the mviews).

**Comment by spficklin** [comment] 2018-08-23 18:13
Referring here to @laceysanderson comment regarding this on another issue: https://github.com/tripal/tripal/issues/500#issuecomment-412712372

**Comment by laceysanderson** [comment] 2019-11-11 03:56
I'm closing this as there has been no progress made in over a year and this is not a bug just a nice feature. If you would like to collaborate on implementing this functionality, I would love to work with you!

**Closed as completed by laceysanderson** 2019-11-11 03:56 UTC
Labels: Community - Enhancement
