### ISSUE TITLE
Job Daemon Status block says "Stopped" but daemon is running

### ISSUE THREAD

**Issue by martacsilva** [tripal/tripal#1140] opened 2020-12-18 16:39 UTC
### System information

* Tripal Version: 7.x-3.4
* Drupal Version: 7.73
* PostgreSQL Version: 9.5.24
* PHP Version: 7.0.33-0ubuntu0.16.04.16

### Issue description
The Job Daemon Status block on my Dashboard is not updating correctly with the actual daemon.  I have stopped and started the daemon and run jobs with and without it, and I haven't had any issues. Other information on the block is correct, however, except for the number of iterations.
I believe this is also resulting in emails getting sent regularly saying that the Daemon has "died". I always check the daemon's status in the command line and the logs, and there's never any issues and it's always running correctly. And I don't know how to stop these emails from getting sent :(

I attached screenshots of the block and of the result of the command `drush trpjob-daemon status`

#### Steps to reproduce
I don't think there's any real steps I can give you to reproduce. I don't usually check the dashboard, so I can't tell you if it was working correctly previously, since this a recent portal.

#### Error messages and screenshots
![Screenshot (71)](https://user-images.githubusercontent.com/47527249/102637669-407b2980-414e-11eb-99a2-553e256948f3.png)
![Screenshot (70)](https://user-images.githubusercontent.com/47527249/102637681-43761a00-414e-11eb-9cba-d7a063f470cd.png)

**Comment by spficklin** [comment] 2021-03-06 02:00
Sorry we failed to give a timely response on this @martacds .  Were you able to resolve it?

**Comment by martacsilva** [comment] 2021-03-08 12:25
Hi,
No problem! Since the job queue is running just fine, it definitely wasn't a top priority. Which means that I haven't devoted much time to trying to fix it and have no further insights into the problem.

Is there any direction you can suggest we head towards for troubleshooting?

Thank you!

**Comment by spficklin** [comment] 2021-03-08 18:25
@laceysanderson since I'm not as up-to-speed with the Tripal Deamon module can you take a stab at this issue?

**Comment by laceysanderson** [comment] 2021-03-12 19:52
Hi @martacds 

I checked the functionality on my server using the development version of tripal 3 and it works as expected.

The block is from the tripal_daemon module and the red "stopped" indicator is caused by [`ps h --pid $PID | wc -l`](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_daemon/includes/tripal_daemon.blocks.inc#L77) in Tripal Daemon. However, the email is sent by Drush Daemon (drushd) and is triggered by [`ps aux | grep "$pid" | grep "daemon" | wc -l`](https://git.drupalcode.org/project/drushd/-/blob/7.x-2.x/includes/drushd.api.inc#L138). The command-line status uses the exact same checking mechanism as the email so it is very weird you are receiving emails despite the command-line saying everything is running fine.

# Troubleshooting

## Block
Can you try running `ps h --pid $PID` after replacing $PID with the pid shown in the status? You should expect to get a single line of output that when piped to `wc -l` will evaluate to `1`. If this works as expected then I would add a debugging line [here](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_daemon/includes/tripal_daemon.blocks.inc#L85) which tells you the value of `$is_running` and `$is_alive`.

## Emails
Can you post a full copy of the email in this thread? I am wondering if the email is specified to the Tripal Daemon or if you accidentally ran `drush daemon start` at some point and then killed the process. This would cause the Drush Daemon module to send you an email indicating that the example daemon was killed and may have nothing to do with the status of the Tripal Daemon. Additionally can you post the details of `drush daemon status`?

**Comment by martacsilva** [comment] 2021-03-15 16:18
Hi @laceysanderson , thank you for the help!

Result for `ps h --pid $PID`
`23750 ?        S      2:08 php /usr/local/bin/drush --root=/var/www/html/drupal/web --uri=http://default daemon start`
and it does indeed evaluate to 1

Email (it's an old one sorry, but nothing has been changed since this):

    Daemon Machine Name: tripal_daemon
    Website: CorkOakDB (URL)

    Dear ,
    We regret to inform you that your tripal_daemon daemon has perished. Although
    we are uncertain as to the cause of his/her death, we have attached their
    last communication of status. We recommend you use drush to restart your
    daemon at your earliest convenience.
    Sincerely,
    ~CorkOakDB

    The last known status for this daemon is:
    PID: 26797
    Hibernating: FALSE
    Number of Iterations: 817
    Current Log File: /tmp/drupal-TripalDaemon_20201207.log
    Running Job: FALSE
    Current Jobs:

`drush daemon status`:
The Daemon is currently stopped
The Daemon has never been run. 

Can't promise that `drush daemon start` wasn't run accidentally at some point :(

**Comment by laceysanderson** [comment] 2021-03-23 14:42
Hmm... the return from `drush daemon status` shows that it wasn't due to `drush daemon start`. Furthermore, the `tripal_daemon` in the email message shows the email is related to the tripal daemon specifically. This is very bizarre considering your execution of ps gave the expected result.

I will look into this further sometime this week.

**Comment by shmenolin** [comment] 2021-06-14 01:35
Is this problem solved? My job daemon status always shows "Stopped" even when the jobs are running without any other details of the job.
Also, how can I set up to receive job notifications as emails?

**Comment by laceysanderson** [comment] 2021-08-06 17:34
**Sorry for the delayed response! I've been away on leave and unable to answer until now.**

Unfortunately, this is not yet fixed. I'm re-adding it to my todo list.

@shmenolin the **Job Daemon** status updates should be automatically set up using the email address of the first account created on your site -the core administrator. This only provides emails if the job daemon is not working and does not include general job information.

**Comment by laceysanderson** [comment] 2022-12-07 03:13
Closing as this will not be fixed in Tripal 3 and may not apply in Tripal 4

**Closed as completed by laceysanderson** 2022-12-07 03:13 UTC
Labels: bug - potential
