### ISSUE TITLE
Creating, Editing and Deleting Tripal Fields Cause 500 Error

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#375] opened 2018-05-17 19:58 UTC
### System information
- Tripal Version: 7.x-3.x (latest)
- Drupal Version: 7.59
- PostgreSQL Version: 9.6
- PHP Version: 7.1

### Issue description
The issue does not happen with Chado and Drupal fields. When deleting a field that's "Supported By" Tripal, we get a 500 error. The same happens when we attempt to edit or delete. This issue only started happening after the latest update to tripal. I am not sure what's causing the issue and the logs don't show anything helpful. In fact I can't find anything in the logs regarding this error!

Any idea what might be causing this?

Thanks!

**Comment by spficklin** [comment] 2018-05-17 20:06
What Field did you try to delete? Is it one that comes with Tripal?

**Comment by almasaeed2010** [comment] 2018-05-17 22:02
I tried multiple fields but I believe `rdfs__type` comes with Tripal.

**Comment by bradfordcondon** [comment] 2018-05-29 13:26
@almasaeed2010  did we try the drush delete field command or only via GUI?

**Comment by almasaeed2010** [comment] 2018-05-29 13:26
No I haven't yet

**Comment by bradfordcondon** [comment] 2018-05-29 13:48
after pulling on master i was able to edit the rdfs:type field as well as create our field of interest (ontology_data).

Not sure if it was fixed or if there was something on our site that changed preventing me from duplicating issue, but closing as resolved for now.

**Comment by bradfordcondon** [comment] 2018-05-29 14:01
reopening: we dont have this issue on our dev site but its on our live site and updating hasn't resolved it :|

**Comment by bradfordcondon** [comment] 2018-05-29 14:28
the field **can** be deleted with drush.

**Comment by bradfordcondon** [comment] 2018-05-29 15:45
I edited the "label" field and brought down our live site :(

Adding error printing all pages have
```
PDOException: SQLSTATE[08006] [7] FATAL: remaining connection slots are reserved for non-replication superuser connections in lock_may_be_available() (line 167 of /var/www/html/includes/lock.inc).
```

I'm thinking hte field edit is doing something crazy taking up all db connections...

**Comment by bradfordcondon** [comment] 2018-05-30 14:17
@almasaeed2010 modified our database settings and now i am able to create the TripalField.  However now when I try to edit it to set the necessary settings I get this error:

```
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) in /var/www/html/sites/all/modules/tripal/tripal/includes/tripal.field_storage.inc on line 116
```

This error occurs on all our TripalFields.  It does not occur for Chado or Drupal fields.

**Comment by bradfordcondon** [comment] 2018-05-30 14:26
```

  // Perform the query and return the results.
  $entities = $select->execute();
  $result = array(
    'TripalEntity' => array(),
  );
  while ($entity = $entities->fetchObject()) {

$ids = array($entity->id, '0', $entity->name);
    $result['TripalEntity'][$entity->id] = entity_create_stub_entity('TripalEntity', $ids);
  }
```
We run out of memory at the `while($entity)` loop.
I think we fetch the name/id of every entity on the site for some reason?  (By we, i mean Tripal's `tripal_field_storage_query`)

**Comment by laceysanderson** [comment] 2018-05-30 14:26
Adding the URGENT tag to indicate the serious nature of this bug...

**Comment by laceysanderson** [comment] 2018-05-30 14:31
Can you link to the code you posted for context?

**Comment by bradfordcondon** [comment] 2018-05-30 14:33
shoot im sorry of course

https://github.com/tripal/tripal/blob/d359971f965e7229708d83d499f64b9b8212f32e/tripal/includes/tripal.field_storage.inc#L69-L121


edit: wow I need to never just copy paste code in again.  This looks rad!

**Comment by laceysanderson** [comment] 2018-05-30 15:23
This section is supposed to restrict it so you are not retrieving all entities but only those specific to your query. 
https://github.com/tripal/tripal/blob/d359971f965e7229708d83d499f64b9b8212f32e/tripal/includes/tripal.field_storage.inc#L81-L95

That said, I'm surprised we're even ending up in this function when adding a field and editing settings... What is the value of `$query->fieldConditions`?

**Comment by bradfordcondon** [comment] 2018-05-30 15:28
when editing  Resource Type (`rdfs_type`):
Array, 0 elements.

here's the fully extended `query`

![screen shot 2018-05-30 at 11 28 03 am](https://user-images.githubusercontent.com/7063154/40730413-8e41415e-63fc-11e8-971e-ce60fd7c74b2.png)


dpm'd at the **start** of the call, ie line 70.

**Comment by laceysanderson** [comment] 2018-05-30 15:52
Wow, that would do it. It would be adding all the entities (not even those of a specific content type) into an array...

@spficklin & @shawnawsu was it expected that `tripal_field_storage_query` would get called when a field is created and settings configured? I would have expected it only on edit/view of an entity instance and views query...

**Comment by bradfordcondon** [comment] 2018-05-30 15:54
I'll point out the fact that this only happens for TRIPAL fields, and not CHADO fields.   Because theres only 1 Tripal field in existence by default some upgrade or mistake was easy to overlook.

This also means that for now, a simple fix is to use CHADO fields instead of Tripal fields.  (i didnt in this case because I intended to make the field back-end agnostic).

**Comment by laceysanderson** [comment] 2018-05-30 15:55
Also, we would have only seen the results when there is a substantial number of entities in the site.

**Comment by bradfordcondon** [comment] 2018-05-30 17:12
deleting a chado field (but not editing) also gives me the out of memory error:

`Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) in /var/www/html/sites/all/modules/tripal/tripal/includes/tripal.field_storage.inc on line 116`

Abdullah says we limit the live site to 512 MB for security reasons.

Is it possible this is connected to the timeout problem #363 ???

seems very likely.  after navigating away from the error, my query `dpm` above triggers.

![screen shot 2018-05-30 at 1 14 56 pm](https://user-images.githubusercontent.com/7063154/40736267-9177bc9a-640b-11e8-92f4-8d942e8630f0.png)

**Comment by spficklin** [comment] 2018-06-12 04:44
Yes, the tripal_field_storage_query gets called when deleting a field because the [field_purge_batch](https://api.drupal.org/api/drupal/modules%21field%21field.crud.inc/function/field_purge_batch/7.x) function is called whenever a field is deleted.  This function then calls the EntityFieldQuery function which then calls the hook_field_storage_query() which if this is a tripal field will call **tripal_field_storage_query** (if it's a Chado field it will call **tripal_chado_field_storage_query**).

I think the problem you are encountering is that the tripal_field_storage_query is not implementing all of the filters properly. I have made a fix on a new branch named **375-Tv3-deleting_fields**.  Can you test it and see if it helps resolve the problem for you?   I have added support to two of the filters that were previously not handled:  the entityCondition (on the bundle name) and the range which limits the query to only 10 records.   I think this should dramatically reduce the number of entities returned when the query runs.

**Comment by spficklin** [comment] 2018-06-12 04:50
If that fix works then I can submit the branch as a pull request.  I'm not 100% sure that will fix hence I did not submit it as a PR.

**Comment by bradfordcondon** [comment] 2018-06-12 12:42
I can confirm this fixes the 500 error on deleting a tripal field.

**Comment by spficklin** [comment] 2018-06-12 15:19
How about the slowness issues you had when deleting fields?

**Comment by bradfordcondon** [comment] 2018-06-12 15:26
we'll have to see: we have different memory settings on live and dev....  site seems ok and i didn't have memory problems after deletion.

**Comment by bradfordcondon** [comment] 2018-06-20 12:59
I'm marking this resolved.

**Closed as completed by bradfordcondon** 2018-06-20 12:59 UTC
Labels: bug - confirmed, Priority - Release Blocker, Priority - URGENT!
