### ISSUE TITLE
Custom Tripal tables unavailable content type

### ISSUE THREAD

**Issue by btski** [tripal/tripal#177] opened 2017-10-26 20:51 UTC

**Comment by spficklin** [comment] 2017-10-28 05:33
Hi @btski .  Apologies for the slow reply on this.  I noticed you closed it without a response and removed the message.  Were you able to figure something out, or would you still like some help?

**Comment by btski** [comment] 2017-10-31 16:37
Response time wasn't an issue. It was just a poorly conceived question. I've been having trouble depositing information into Chado with the bulk loader, likely due to constraints on input data. I should be able to sort that out, but I've shifted focus to creating a custom Chado table to house all of my metadata (some of which fails to fit well within the existing Chado schema). I'm planning to populate the base Chado tables as well as possible, but I'll also have all metadata stored within a custom table for easier access. 

Currently, I'm trying to figure out how to create a 'Content Type'. By default, Tripal allows new content to link to 20 Chado tables. Most of the available tables are not represented. I've successfully loaded sample data onto my custom table (using the bulk loader), but I'm unable to access it. For reference: I'm storing everything on an AWS instance and am using Tripal v3. To create a new page, I'm going to the 'Structure' tab --> 'Tripal Content Types' --> 'Add Tripal Content Type' --> reference an ontology (I'm using 'Database') --> select Chado table (20 available options, new Chado table unavailable). Also, I'm not entirely sure how the pages work (in terms of displaying data linked to Chado tables). I've been able to deposit and sync/publish organism data (using the bulk loader and following instructions on the Tripal site), but when I successfully load authors into the 'Contact' table I'm unable to publish the data (zero records published).

Thanks for help in advance @spficklin or whoever else happens to see this. I also appreciate that you followed up with my original post despite my attempts to remove it.

Edited for clarification.

**Comment by spficklin** [comment] 2017-11-03 17:45
Okay, it looks like we have a bug here with custom tables now showing up in that list for creating new content types.  I've marked this as a bug and task to look at.   

Can you describe your custom tables and the data you're putting into them?

**Comment by btski** [comment] 2017-11-03 18:16
My metadata consists of an automatically generated unique ID, genBank accession (if available), strain/isolate name, strain/isolate source, genotype, author/s, collection location, and collection date. Some of this should fit within existing Chado tables (and link together). However, I've been having trouble depositing data (likely due to null field values or incompatible characters). My solution was to deposit all of my metadata into a single custom Chado table to make it easily searchable (and not have to worry about field restrictions). I was also going to populate Chado tables that interface with Tripal modules (such as BLAST), resulting in some redundancy. Hopefully I'll be able to link everything together (associate the metadata with the corresponding raw DNA and translated features).

I'm particularly interested in having my metadata in a single table in order to perform multi-variable searches/queries. When looking through other Tripal sites, I found several sites that employ similar search parameters, indicating searches among tables can be achieved. However, they were limited to queries of a single data type. I've noticed that you are able to perform multi-variable searches of data stored within the same table (example: Organism table, query species and genus simultaneously). I want to mimic this behavior without mislabeling data fields (inputing the collection date in the organism table under species, for example).

Example search options:
https://www.cottongen.org/find/germplasm/collection
http://www.cacaogenomedb.org/shrs/

It seems that both sites use an embedded PHP script to query the postgreSQL database directly. I was planning to do something similar (although I have zero experience with PHP/HTML/Javascript and limited SQL knowledge). If custom tables become available content types, that would be quite helpful. Thanks @spficklin!

PS: Should I reopen this topic for the sake of visibility? It's currently closed.

Edit - Went ahead and reopened topic. Wasn't sure if I would be able to myself.

**Comment by spficklin** [comment] 2017-11-03 22:38
I think, @btski, that you can store all of your meta data in regular Chado tables.  What you describe sounds typical of what other folks are storing without creating custom tables.  One suggestion would be to reach out on the Chado mailing list to ask how other folks are storing similar data.  https://sourceforge.net/projects/gmod/lists/gmod-schema.   One advantage of storing data in similar ways as other folks is that if other groups put out extension modules that are appropriate for your data types, it will be more likely to be useful if you're following a command method.  

In terms of searching, If you are using Tripal v3 you might find the Drupal Views integration can get you a bit further than expected.  For every content type you create you get a default search that automatically appears.  You can customize and tweak them.  Just about every field associated with the content type can be used to build the search from.  It is much more flexible than Tripal v2, and it may help negate the need to program a custom search tool like you've seen on other sites.

**Comment by btski** [comment] 2017-11-06 15:58
Thanks for the input @spficklin. I've attempted to contact the Chado mailing list and did not receive a response. I've tried to categorize my data to corresponding Chado tables/features but there's no guaranteed agreement with community consensus. I'll look into Drupal views. Thanks for the suggestion.

**Comment by spficklin** [comment] 2017-11-06 21:19
If you want to post a new issue requesting feedback on your storage design I can try to ping a few folks to give you feedback on it.

**Comment by laceysanderson** [comment] 2018-05-30 23:19
Closing this as there has been no movement on it for 7 months. Please re-open if you would like to continue the discussion :-)

**Comment by spficklin** [comment] 2018-06-01 17:49
I'm going to re-open this issue because I think we may still have an issue.  I can confirm that custom tables can be used for creating new content types.  That now works, so @btski I think the premise of the issue title is resolved.  

However, a custom table can only be considered a "base" table and hence used to store content types if the table has a type_id column that has a proper foreign key to the cvterm table and if the table is not a linker table (e.g. xx_relationship, xx_dbxref, xx_cvterm, xxprop).  There are some chado tables that do not have a type_id but that we consider a "base" table:  organism, project, analysis, biomaterial, eimge.  Those have a hard-coded exception.  However, there's no way to create an exception for a custom table.  So my question is....

Should we create a hook or a setting on the custom table creation page that lets a user override our exceptions for what Tripal considers a base table?  Or should we require that every base table should always have a type_id?

**Comment by btski** [comment] 2018-06-27 19:47
It's probably fair to assume every base table can be assigned a type_id. I believe we were trying to strongly enforce the usage of ontologies to make schema structure more legible. Having type_id as a required field for custom tables seems to follow that objective.

**Comment by spficklin** [comment] 2018-06-29 18:22
Unfortunatley, @btski , Chado was not designed such that every base table has a type_id.  For example neither the analysis or project tables have a type_id.   Tripal can support it either way... even for custom tables.

**Comment by laceysanderson** [comment] 2018-11-11 17:58
> However, a custom table can only be considered a "base" table and hence used to store content types if the table has a type_id column that has a proper foreign key to the cvterm table and if the table is not a linker table (e.g. xx_relationship, xx_dbxref, xx_cvterm, xxprop). There are some chado tables that do not have a type_id but that we consider a "base" table: organism, project, analysis, biomaterial, eimge. Those have a hard-coded exception. However, there's no way to create an exception for a custom table. So my question is....
> 
> Should we create a hook or a setting on the custom table creation page that lets a user override our exceptions for what Tripal considers a base table? Or should we require that every base table should always have a type_id? 

I think a setting on the custom table creation page would be the most intuitive. We should also allow this setting to be set programmatically of course for custom tables created by modules.

**Comment by spficklin** [comment] 2019-04-23 16:58
This is low hanging fruit, so I'm tagging for a fix for v3.2 release.

**Comment by spficklin** [comment] 2019-04-27 00:43
Okay, I thought this would be low-hanging fruit but it was more involved than I thought.  But I have a PR for it.

**Comment by laceysanderson** [comment] 2019-11-11 19:56
@spficklin just checking in on this one. The PR is still waiting for some changes and this functionality has been requested by a number of people.

**Comment by bradfordcondon** [comment] 2020-05-12 22:21
note work started in `117-tv3-custom_tables_as_base`

**Comment by laceysanderson** [comment] 2022-12-07 02:46
Closing as this is now outdated.

**Closed as completed by laceysanderson** 2022-12-07 02:46 UTC
Labels: Community - Discussion
