### ISSUE TITLE
Analysis field not working

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#1913] opened 2024-06-20 16:00 UTC
### Tripal Version

4.x

### Drupal Version

10.x

### PostgreSQL Version

15.1

### PHP Version

8.1.2

### General Description

**Bug 1**. The analysis field does not create a record in the Drupal field table, but does create a record in Chado.  This creates a problem because it doesn't show up on the entity page (e.g. on a project page) after the user added it.  Then when the user tries to add it again because it didn't work the first time, there is an error that a unique constraint is violated (in the recent logs) and it can't update the entity.

### I have given Bug 2 its own issue: #1920 and copied all of the relevant comments there

~~**Bug 2.** When editing an entity, the "Remove" button will remove a linked entity (e.g. remove analysis from project) in the Drupal table, but does not delete it from the underlying chado linker table. If instead it is changed to `-- Select --` then it is removed from both the Drupal and Chado tables. This is because the "Remove" button removes the item from the form state so then Chado storage doesn't know it existed and doesn't know to delete it in Chado.~~

### Steps to reproduce Bug 1

1. Create an analysis entity
2. Create a project entity.
3. Edit the project entity and add the analysis to it.
4. The analysis field will not show up on the page.
5. Look in the Drupal field table, a record for it is missing.
6. Look in the Chado `project_analysis` table and there is a record for it.

### Error messages

```shell
PDOException: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "project_analysis_c1" DETAIL: Key (project_id, analysis_id)=(2, 1) already exists
```

### Screenshots

![image](https://github.com/tripal/tripal/assets/1719352/09ee060f-dc54-4c56-8cc2-daa5c94ae581)

Bug 1 was somehow introduced by PR #1882
`git checkout e8d74534681abe51c088c06e38e2e2599fa7c4e8 .` = works
`git checkout 75ab06d888c839ef34affc5e9cd19ca7e0f491a2 .` = works
`git checkout 96d15dd05a5341c06cb05bb7f83c5550fc166366 .` = does not work

### I have given Bug 2 its own issue: #1920 and copied all of the relevant comments there

1. Create an analysis entity
2. Create a project entity and link the analysis when creating it.
3. Edit the project entity and click the "Remove" button next to the analysis, and save.
4. Check the `project_analysis` table,, the record is still there

**Comment by dsenalik** [comment] 2024-06-20 16:14
I can't reproduce this bug, it is working for me.
I created the project with analysis linked.
(Edit: Bug 1 appears if you edit existing project and then add analysis, I updated the issue to reflect this)
I edited and added a second analysis.
I edited and changed the order.
Everything working as expected.
Tested on Drupal 10.3 PHP 8.3 Postgres 13
![2024-06-20_project](https://github.com/tripal/tripal/assets/8419404/b16f69c8-cc42-4f98-892d-06fa93c889eb)
This was on a docker on the `tv4g1-issue1900-remove-duplicated-yaml` branch but that is pretty recent

**Comment by dsenalik** [comment] 2024-06-20 16:18
### Transferred this bug to issue #1920
I do see bug 2 if I edit and remove the second analysis with the "Remove" button. Display does not show analysis 2, but it should have. However, it is added to the linker table
```
sitedb=> select * from project_analysis;
 project_analysis_id | project_id | analysis_id | rank 
---------------------+------------+-------------+------
                   4 |          1 |           2 |    1
                   6 |          1 |           1 |    1
(2 rows)
```

**Comment by dsenalik** [comment] 2024-06-20 16:41
### Transferred this bug to issue #1920

Bug 2. It seems when you remove one linked record, it is not included in the delete queries.
I have three analyses on the project and delete the third one.
It is not included in the delete queries, there should be three of them, so it persists in the linker table
![2024-06-20_only_two](https://github.com/tripal/tripal/assets/8419404/59aee303-3123-4b50-ac2e-1a75c92b0049)

I wonder if bug 2 has been here for a while and we never tested the right case 🙈, delete a linked record, then try to re-add it. 

I wonder if the delete query for chado storage should just be `DELETE FROM {chado.project_analysis} WHERE project_id = :placeholder`

**Comment by dsenalik** [comment] 2024-06-20 16:53
### Transferred this bug to issue #1920

Here is an interesting complication for Bug 2. I removed the third analysis with the "Remove" button.
If instead you remove it by changing to "-- Select --" then it is properly removed from the linker table.
So the "Remove" button removes it from the returned form state and we don't know that it needs to be removed. Changing it to "-- Select --" leaves it in the form state, so we know to delete it.
![2024-06-20_only_two png2024-06-20_select-only](https://github.com/tripal/tripal/assets/8419404/fa2c1e87-62b4-4623-be3f-7694a195e62b)

**Comment by dsenalik** [comment] 2024-06-20 18:12
### Transferred this bug to issue #1920

My draft PR #1914 for Bug 2 was a failure, if there is not at least one record in the form state then no code is called and nothing gets deleted. A new approach is needed.

**Comment by dsenalik** [comment] 2024-06-21 16:32
### Transferred this bug to issue #1920

I'm not going to work on this right away, but my thought on how to tackle Bug 2 is to add a hidden field to the form for all cardinality > 1 items, which will persist in the form state even if a line is removed. Then we will be able to delete in Chado items that the user has removed.

**Comment by dsenalik** [comment] 2024-06-25 12:49
I think **Bug 1** is caused by this change in PR #1882 - file `tripal_chado/src/TripalStorage/ChadoRecords.php`
![2024-06-25_why](https://github.com/tripal/tripal/assets/8419404/134d4290-373b-4b13-89b7-5b5a12d4fe80)

This change caused the `has_values` indicator to not be set.
Changing it back
```
           // $this->records[$base_table]['tables'][$table_alias]['items'][$delta]['values'][$column_alias] = $record_id;
              $this->setColumnValue($base_table, $table_alias, $delta, $column_alias, $record_id);
```
and I can save a contact on a project.
But I don't know if there are other side effects.

**Comment by dsenalik** [comment] 2024-06-27 23:26
I created a ~~draft~~ PR #1921 so we can test and discuss whether what I changed here is correct.

**Closed as completed** 2024-09-05 15:46 UTC
Labels: bug - confirmed, Group 1 -  Tripal Content Types | Terms | Fields, Group 2 - Data Storage | Tripal DBX | Chado
