### ISSUE TITLE
Wrong CDS sequence order

### ISSUE THREAD

**Issue by abretaud** [tripal/tripal#415] opened 2018-06-06 16:50 UTC
### System information

* Tripal Version: 2.x
* Drupal Version: 7.59
* PostgreSQL Version: 9.5
* PHP Version: 7.2.4

### Issue description

Hi,
I have a problem with one of our tripal 2 instance where the "Coding sequence (CDS) from alignment" displayed for some mRNA is wrong. After looking into it, it seems like it happens for mRNA on reverse strand. The sequence computed by tripal is composed of all the CDS blocks defined in the gff I loaded, but the CDS are in the wrong order, ie, the last CDS is displayed first, the first is displayed last, etc.
So the CDS sequences looks like KLMNFGHIJABCDE instead of ABCDEFGHIJKLMN.
Here's a sample of GFF that should allow to reproduce the bug.
I suspect the problem to be at https://github.com/tripal/tripal/blob/7.x-2.x/tripal_feature/api/tripal_feature.api.inc#L385 where the sequence is concatenated before doing the reverse complement. If it's the case (not sure), the same code is [still in tripal 3](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/api/modules/tripal_chado.feature.api.inc#L433), so I guess the bug will still be there too (haven't had the time to test though)

```
SomeContig	maker	gene	2723762	2730550	.	-	.	ID=FOOBAR9;Name=FOOBAR9
SomeContig	maker	mRNA	2723762	2730550	.	-	.	ID=FOOBAR9-RA;Parent=FOOBAR9;Name=FOOBAR9-RA
SomeContig	maker	three_prime_UTR	2723762	2724226	.	-	.	ID=FOOBAR9-RA:three_prime_utr;Parent=FOOBAR9-RA
SomeContig	maker	exon	2723762	2724371	.	-	.	ID=FOOBAR9-RA:exon:12912;Parent=FOOBAR9-RA
SomeContig	maker	CDS	2724227	2724371	.	-	1	ID=FOOBAR9-RA:cds;Parent=FOOBAR9-RA
SomeContig	maker	exon	2724568	2724639	.	-	.	ID=FOOBAR9-RA:exon:12911;Parent=FOOBAR9-RA
SomeContig	maker	CDS	2724568	2724639	.	-	1	ID=FOOBAR9-RA:cds;Parent=FOOBAR9-RA
SomeContig	maker	exon	2725283	2725497	.	-	.	ID=FOOBAR9-RA:exon:12910;Parent=FOOBAR9-RA
SomeContig	maker	CDS	2725283	2725497	.	-	0	ID=FOOBAR9-RA:cds;Parent=FOOBAR9-RA
SomeContig	maker	exon	2725815	2725956	.	-	.	ID=FOOBAR9-RA:exon:12909;Parent=FOOBAR9-RA
SomeContig	maker	CDS	2725815	2725956	.	-	1	ID=FOOBAR9-RA:cds;Parent=FOOBAR9-RA
SomeContig	maker	exon	2726339	2726472	.	-	.	ID=FOOBAR9-RA:exon:12908;Parent=FOOBAR9-RA
SomeContig	maker	CDS	2726339	2726472	.	-	0	ID=FOOBAR9-RA:cds;Parent=FOOBAR9-RA
SomeContig	maker	exon	2726658	2726796	.	-	.	ID=FOOBAR9-RA:exon:12907;Parent=FOOBAR9-RA
SomeContig	maker	CDS	2726658	2726796	.	-	1	ID=FOOBAR9-RA:cds;Parent=FOOBAR9-RA
SomeContig	maker	exon	2727010	2727220	.	-	.	ID=FOOBAR9-RA:exon:12906;Parent=FOOBAR9-RA
SomeContig	maker	CDS	2727010	2727220	.	-	2	ID=FOOBAR9-RA:cds;Parent=FOOBAR9-RA
SomeContig	maker	exon	2727432	2727547	.	-	.	ID=FOOBAR9-RA:exon:12905;Parent=FOOBAR9-RA
SomeContig	maker	CDS	2727432	2727547	.	-	1	ID=FOOBAR9-RA:cds;Parent=FOOBAR9-RA
SomeContig	maker	exon	2727632	2727720	.	-	.	ID=FOOBAR9-RA:exon:12904;Parent=FOOBAR9-RA
SomeContig	maker	CDS	2727632	2727720	.	-	0	ID=FOOBAR9-RA:cds;Parent=FOOBAR9-RA
SomeContig	maker	exon	2727909	2728043	.	-	.	ID=FOOBAR9-RA:exon:12903;Parent=FOOBAR9-RA
SomeContig	maker	CDS	2727909	2728043	.	-	0	ID=FOOBAR9-RA:cds;Parent=FOOBAR9-RA
SomeContig	maker	exon	2728242	2728440	.	-	.	ID=FOOBAR9-RA:exon:12902;Parent=FOOBAR9-RA
SomeContig	maker	CDS	2728242	2728440	.	-	1	ID=FOOBAR9-RA:cds;Parent=FOOBAR9-RA
SomeContig	maker	exon	2728624	2728709	.	-	.	ID=FOOBAR9-RA:exon:12901;Parent=FOOBAR9-RA
SomeContig	maker	CDS	2728624	2728709	.	-	0	ID=FOOBAR9-RA:cds;Parent=FOOBAR9-RA
SomeContig	maker	exon	2728808	2728903	.	-	.	ID=FOOBAR9-RA:exon:12900;Parent=FOOBAR9-RA
SomeContig	maker	CDS	2728808	2728903	.	-	0	ID=FOOBAR9-RA:cds;Parent=FOOBAR9-RA
SomeContig	maker	exon	2729033	2729219	.	-	.	ID=FOOBAR9-RA:exon:12899;Parent=FOOBAR9-RA
SomeContig	maker	CDS	2729033	2729219	.	-	1	ID=FOOBAR9-RA:cds;Parent=FOOBAR9-RA
SomeContig	maker	CDS	2729380	2729432	.	-	0	ID=FOOBAR9-RA:cds;Parent=FOOBAR9-RA
SomeContig	maker	exon	2729380	2729533	.	-	.	ID=FOOBAR9-RA:exon:12898;Parent=FOOBAR9-RA
SomeContig	maker	five_prime_UTR	2729433	2729533	.	-	.	ID=FOOBAR9-RA:five_prime_utr;Parent=FOOBAR9-RA
SomeContig	maker	exon	2729998	2730163	.	-	.	ID=FOOBAR9-RA:exon:12897;Parent=FOOBAR9-RA
SomeContig	maker	five_prime_UTR	2729998	2730163	.	-	.	ID=FOOBAR9-RA:five_prime_utr;Parent=FOOBAR9-RA
SomeContig	maker	exon	2730362	2730550	.	-	.	ID=FOOBAR9-RA:exon:12896;Parent=FOOBAR9-RA
SomeContig	maker	five_prime_UTR	2730362	2730550	.	-	.	ID=FOOBAR9-RA:five_prime_utr;Parent=FOOBAR9-RA
```

**Comment by spficklin** [comment] 2018-06-07 20:46
Thanks for reporting this.  We'll test it and see what kind of fix we can make.

**Comment by mdondrup** [comment] 2018-06-08 07:14
Hi, I remember now that we have seen a similar effect in #106 which is possibly related. I would also check the correctness of the tripal core API function that returns the spliced mRNA sequence. I remember that it was not always giving the correct sequence, but I couldn't reproduce it right now. It seems that the examples from #106 are now working correctly in 2.1.

**Comment by abretaud** [comment] 2018-06-08 07:53
Just a note on this bug: it happens also for an mRNA on + strand (on the same contig of the same genome).
So I guess it has to do with [this sql query](https://github.com/tripal/tripal/blob/7.x-2.x/tripal_feature/api/tripal_feature.api.inc#L202) and how it's called (but it scares me)

**Comment by spficklin** [comment] 2018-06-12 03:35
@abretaud for quick testing, using your GFF file above, can you share a test sequence for the "SomeContig"?

**Comment by spficklin** [comment] 2018-06-17 09:03
@abretaud I'm having a hard time reproducing this one. I'd like to get this fixed before our next release of both Tripal v2 and Tripal v3.  I cannot reproduce the problem.   Can you send me the full contig/chromosome sequence and the correct transcript sequence?  If you prefer to do that privately feel free to email those to me directly.

**Comment by abretaud** [comment] 2018-06-19 12:51
Sorry for the delay, too many things to do these days...
I've just tried to create some minimal test data, but couldn't reproduce the bug either. I guess there's something else involved, I'll make moer tests and let you know when I have something reproducible

**Comment by spficklin** [comment] 2018-06-19 18:20
Okay, well at least this got some other fixes into Tv3 from this :-)   I'll take off the release blocker label, but leave it open a bit longer so you can report on testing.

**Comment by spficklin** [comment] 2018-06-29 20:21
The fix for CDS field has been merged into Tv3. Now we're just waiting to see if this problem can be duplicated.

**Comment by abretaud** [comment] 2018-06-29 21:22
@spficklin Did you receive my email with some test data?

**Closed as completed** 2018-09-21 21:07 UTC
Labels: bug - confirmed, waiting on submitter

**Comment by bradfordcondon** [comment] 2018-09-21 21:08
merged on both branches, thank you!
