### ISSUE TITLE
Is there a way to programmatically create a text chado field in a bundle? 

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#507] opened 2018-07-11 23:38 UTC
Is there a simple way to programatically create a text field (Chado Field) and attach it to a bundle? I can't seem to find an example of this. I tried creating a custom field but only to realize that this actually creates a literal custom field and seems overkill for my current needs. Please advise?

Tagging @bradfordcondon since he might already have tried this

**Comment by bradfordcondon** [comment] 2018-07-12 00:18
is it possible that a chado property would work for what you want to do?

If all you want is to have a variable that displays a value, then chado property field is the way to go.

For example, to attach a "affiliation" field to contact, where the value will be the name of the university.


Put another way... where would the value be stored?  If in Chado, where?

**Comment by risharde** [comment] 2018-07-12 00:21
Yes, exactly, at least at this primitive point in my understanding, a good
start would be a simple chado property field. I could be wrong but this
value could be store in the contactprops table

Any ideas how to get this done?

**Comment by bradfordcondon** [comment] 2018-07-12 00:25
programmatically all you have to do is insert a chado property, and Tripal will "discover" the field when the user presses the "check for new fields" button.

So insert a chado property with a new cvterm (say, local:user_password) and a value.  Then, check for new fields on the bundle you inserted the property (if you inserted into contactprops, then the contact bundle).  It should autodsicover it and provide a simple text display and text input widget.  The field type will be chado property.

You can also manually create a field for the property using the GUI, but you said you wanted to do it programmatically...

Note my biosample fields below: all of the fields of type chado property were autodiscovered.

<img width="1388" alt="screen shot 2018-07-11 at 8 24 37 pm" src="https://user-images.githubusercontent.com/7063154/42605901-806a22f4-8548-11e8-8463-d36f561b9338.png">

**Comment by risharde** [comment] 2018-07-12 01:14
Thanks Bradford, any chance you can point me to sample code on doing so or
is this available in the Tripal docs somewhere?

**Comment by risharde** [comment] 2018-07-16 16:34
Tagging @bradfordcondon @spficklin @shawnawsu 
Any example code on creating a simple text field chado property via Tripal API code that will hook on a specific Tripal Content Type?

Specifically, I need to be able to add fields that will add data to the contactprops table

**Comment by bradfordcondon** [comment] 2018-07-16 18:53
Hi @risharde sorry for slow responses, on vacation.


Adding a property will automatically create a field on the appropriate content type.

the below code is from tripal analysis interpro (adding a property to an analysis record: note that the chado_insert_property call knows automatically that the table will be analysisprop.)

```php

  $record = array('table'=> 'analysis', 'id' => $node->analysis_id);

  // Add the analysis type.
  chado_insert_property($record, array('type_name' =>'Analysis Type', 'cv_name' => 'analysis_property', 'value' => 'interpro_analysis'));
```

Once there is a record associated with the property, the field will be discovered when you press check for new fields.

In your case, you may have to create a NULL record and associate the property with it to get the field to show up the first time, if that makes sense.

**Comment by risharde** [comment] 2018-07-16 20:46
Thanks Bradford! Hope you had an awesome vacation, thank you so much for
this, I was searching through code randomly and would have probably never
come across this. I'll let you know if this works, you're a life saver!

2 more subsequent questions to that is:
a. Does this automatically insert the type_id of the property being inserted in some way? If not, how would I be able to assign an type_id, please let me know
b. Also, would there be an automated way of doing the check fields so that I don't have to click on it? If you do know, please let me know

Thanks so much @bradfordcondon

**Comment by risharde** [comment] 2018-07-17 01:04
Hi @bradfordcondon , so in order to add the property, I have to get over the hurdle of creating the node. Would normal drupal node creation programming work or is there sample code to create a node for Tripal. Please let me know. I've been able to submit a record which get's saved in the contact table BUT it doesn't show up on the Tripal Content section so it seems I'm doing something wrong. 

The code I used was
`
			$values = array(
				'name' => 'Temporary name',
				'description' => 'Temporary Description',
			);
			$node = chado_insert_record('contact', $values);
`

**Comment by laceysanderson** [comment] 2018-07-17 17:09
Hi @risharde,

You don't actually need a node -sorry about the confusion caused by the variable name! What you need is a chado record in the main table (in the example, the analysis table). See the edited example below.

```php
// Add a null record to the analysis table if you don't have an existing record to work with (saved in analysis).
$values = array(
  'name' => 'null',
);
chado_insert_record('analysis', $values);

// Add a property to the analysis (saved in chado.analysisprop).
$primary_record = array('table'=> 'analysis', 'id' => $analysis_id);

chado_insert_property(
  $record, 
  array(
    'type_name' =>'Analysis Type',         // the cvterm.name to lookup type_id
    'cv_name' => 'analysis_property',     // the cv.name to lookup type_id
    'value' => 'interpro_analysis'             // the actual value of the property.
));
```
For reference, see [chado_insert_record](http://api.tripal.info/api/tripal/tripal_chado%21api%21tripal_chado.query.api.inc/function/chado_insert_record/3.x) and [chado_insert_property](http://api.tripal.info/api/tripal/tripal_chado%21api%21tripal_chado.property.api.inc/function/chado_insert_property/3.x).

By the way, I suggest using the property type you actually want from the beginning since the type_id is used in the machine name of the property field.

**Comment by risharde** [comment] 2018-07-17 21:53
Thanks @bradfordcondon , I tried something similar to this but when I did that, it didn't show up on Find Tripal Content for some reason. Do you think this is normal behaviour? I can see the record is created in contact table but yet it is not listed in the Find Tripal Content table. I was able to make it show up on Find Tripal Content but when I did that, it created what seems to be a node and did not create the record

Code which is most likely wrong:

> 

			$values = array(
				'schema__name' => 'Temporary name',
				'schema__description' => 'Temporary Description',
			);
			$node = tripal_insert_entity($bundle->name, $values);

**Comment by shawnawsu** [comment] 2018-07-18 09:52
I think Bradford is on vacation still, just as an FYI. 

I'm a bit confused. Are you trying to create a new field or new content? If you've inserted the property into the chado prop table as Lacey described you'd need to edit the tripal content type (admin/structure/bio_data/manage/bio_data_#/fields)and click 'check for new fields' to add the field to the content type.

**Comment by risharde** [comment] 2018-07-18 10:42
Just to clarify, I am trying to programmatically create a trial content
type, add fields programmatically to the newly created content type and
then submit data programmatically.

It has to be done in such a way that the end user can then administer the
data submitted via the UK interfaces.

**Comment by shawnawsu** [comment] 2018-07-18 11:15
Which tripal version is this?

**Comment by risharde** [comment] 2018-07-18 11:51
Tripal 3

**Comment by bradfordcondon** [comment] 2018-07-18 17:48
```
		$values = array(
			'schema__name' => 'Temporary name',
			'schema__description' => 'Temporary Description',
		);
		$node = tripal_insert_entity($bundle->name, $values);

```

where is this code being executed?

As @laceysanderson pointed out, the `node` was a red herring, the code example she points out is great.  Replacing analysis with contact should work just fine.  


> I can see the record is created in contact table but yet it is not listed in the Find Tripal Content table

In that case, you need to publish your contact records.  This checks the chado.contacts table and checks if there are records that dont have corresponding entities.  Visit `admin/content/bio_data/publish`and select contact.

Once you do that, press the "check for new fields" button in the contacts bundle area.  The property you added should appear as a new field.

**Comment by risharde** [comment] 2018-07-18 18:56
Thanks @laceysanderson and @bradfordcondon for the code and input, I'll try it out and let you know if it works according to plan

**Comment by risharde** [comment] 2018-07-18 19:52
@bradfordcondon and @laceysanderson 
So I tried the code below since I saw there was already a contact record with id = 1 and name = null and description = null
But the code doesn't seem to create the property, any ideas, I searched for the cvterm.name in the cvterm table and also the cv.name from the cv table, i'm hoping that is right?

LOG shows: chado_get_property: Cannot find the term described by: Array ( [type_name] => Organization [cv_name] => contact_property [value] => #default ) .

> 

			$record = array('table' => 'contact', 'id' => 1);
			
			//Add Organization Property with #default value
			$status = chado_insert_property(
			  $record, 
			  array(
				'type_name' =>'Organization',         // the cvterm.name to lookup type_id
				'cv_name' => 'contact_property',     // the cv.name to lookup type_id
				'value' => '#default'             // the actual value of the property.
			));
			
			if($status) {
				dpm("Organization property created");
			}
			else {
				dpm("Organization property not created");
			}

**Comment by risharde** [comment] 2018-07-18 20:03
I'm going to try 'tripal_contact' as the cv_name and see if that works in the meantime

**Comment by bradfordcondon** [comment] 2018-07-18 20:06
double check the cvterm and associated CV exist, as that error suggests it couldnt find the term.  That said you're on hte right track.  check `contactprop` after it runs and if you've got your property in there, you should be able to discover the field!

**Comment by risharde** [comment] 2018-07-18 20:09
That worked, so basically for the lay man who is now getting into understanding Tripal
the type_name is from the cvterm table's name
the cv_name can't just be a name from cv.name. It has to be looked up by using the cvterm.cv_id and finding the corresponding cv.name from the cv_id.

**Comment by bradfordcondon** [comment] 2018-07-18 20:13
You don't have to look it up, but it must be the cv name corresponding to the cvterm you are trying to associate.

This is because you might have two cvterms with the same `name` value.   (Imagine the Sequence ontology has the term gene, and your custom module's custom cv also uses a term named gene). Specifying the CV it came from allows you to differentiate them.

If the cvterm and cv you supply don't match (ie the cvterm.cv_id belongs to a different cv) then yes it should fail.

**Comment by bradfordcondon** [comment] 2018-08-06 00:08
looks like your question has been answered: closing.  If not please let us know.

**Closed as completed by bradfordcondon** 2018-08-06 00:08 UTC
Labels: Community - Question
