### ISSUE TITLE
Views integration missing filters

### ISSUE THREAD

**Issue by guignonv** [tripal/tripal#176] opened 2017-10-25 10:42 UTC
Branch: Tripal 7.x-2.x
Module: tripal_views

Today, I just noticed a weird bug related to views integration. In my Tripal instance, I overriden some integrations for several reasons a long time ago. Yesterday, I needed to add a relationship to my custom integration of "stock" table. I did so and noticed some of my views were messed up.

I had a "Broken/missing handler (= 46774)" in the "Filter criteria" section of my view on stocks where I was supposed to have "Chado Stock: Type Id (= 46774)". So I had a look to the "stock" views integration and noticed that I had "Select a filter handler" for both the name field and the type_id field. Then I tried to select the valid filter handler but noticed that it was gone: I could only select Drupal filter handlers and not Tripal ones! :-/ "tripal_views_handler_filter_select_cvterm" and "tripal_views_handler_filter_select_string" were gone.

I checked on my production site: same issue, the handlers were missing BUT the view was working and didn't display any broken thing! So Drupal knew about those handlers while the Tripal interface for views integration did not.

I don't know what happened, nor when, but it seems those handlers disapeared and after a morning of code investigation, I pointed out that "tripal/tripal_views/includes/tripal_views_integration_UI.inc" was missing those filters at line 1402.
`  $handlers[] = 'tripal_views_handler_filter_select_cvterm';
  $handlers[] = 'tripal_views_handler_filter_select_string';
`
After patching the file and clearing the cache, I was able to select again those handlers and all went back to normal. Maybe those lines should be added? Maybe some others are missing (for other handlers than the filter ones)? Maybe the auto-discovery system of handlers is not working as expected? Dunno...

**Comment by spficklin** [comment] 2017-10-30 22:29
Thanks @guignonv.  This is an interesting bug because there has been no change to that bit of code in several years.  Could it have been several years since you last noticed this?  Can you confirm?

If so, then perhaps your solution works, but we'd have to add a few more handlers to the list.

@laceysanderson Any thoughts on this one?

**Comment by guignonv** [comment] 2017-11-03 11:48
Yes, it could have been several years before I noticed it.

**Comment by laceysanderson** [comment] 2017-12-12 17:18
That's very weird that those lines simply disappeared. I can confirm that they should be added back although it will take a little detective work to determine if any additional filters are missing. I'll try to get around to creating an official patch at the very least.

**Comment by laceysanderson** [comment] 2019-03-20 03:20
I seem to remember this being fixed... @guignonv can you confirm?

**Comment by guignonv** [comment] 2019-03-21 09:19
I don't think it has but if nobody else reports the issue, it's not a big deal then as I kind of fixed it on my site. It was just 2 lines missing. I created a PR #902.

**Comment by laceysanderson** [comment] 2019-03-21 15:31
Thanks for the PR, I'll review today :-) Just trying to clean up old issues and make sure everything was resolved.

**Comment by spficklin** [comment] 2019-04-23 16:56
Looks like the PR got merged in! I'm closing this.

**Closed as completed by spficklin** 2019-04-23 16:56 UTC
Labels: bug - confirmed
