### ISSUE TITLE
Call to undefined function chado_get_schema_name()

### ISSUE THREAD

**Issue by georgelouk** [tripal/tripal#1191] opened 2021-04-14 10:37 UTC
## BUG/ERROR report

Hello,

I've manually installed the latest drupal 7 version and all required modules and when i enable tripal chado views i get an error.

It seems that chado_get_schema_name is not included in tripal_chado_views.views.inc

### System information

* Tripal Version: 7.x.3.5
* Drupal Version: 7.79
* PostgreSQL Version: 9.2.24
* PHP Version: 7.2

#### Steps to reproduce

1) Install drupal & the required modules
2) Enable Tripal Chado Views

#### Error messages and screenshots

```
Call to undefined function chado_get_schema_name() in tripal_chado_views_views_data() (line 121 of /home/oqvkyiqz/public_html/tripal/sites/all/modules/tripal/tripal_chado_views/tripal_chado_views.views.inc).
```

**Comment by CarrotOmics** [comment] 2021-04-14 13:23
I don't know how much this helps, but on my site I find the function defined at line 2073 of
```sites/all/modules/tripal/tripal_chado/api/tripal_chado.query.api.inc```

My mistake yesterday was forgetting to clear all caches, have you tried that?

**Comment by georgelouk** [comment] 2021-04-14 14:06
Yes i found it there too. I copied the function inside the tripal_chado_views.views.inc and then it proceed, and another function was missing too (from another file). 
I copied also the other function inside, and then i didn't get the errors but i couldn't actually install chado (after installation process, it was saying again install chado instead of prepare)

**Comment by spficklin** [comment] 2021-04-14 15:56
@georgelouk .  We've never had this reported before, and honestly, I'm not sure where to begin to help debugging.  Let me run a test installation myself to make sure this doesn't happen to me and somehow there's not a bug in the install process.

**Comment by georgelouk** [comment] 2021-04-14 16:17
I've made many installations in both local and real webserver environment (having cpanel) and all the times i've got this error.
Drupal and modules all installed from the official drupal site.

**Comment by spficklin** [comment] 2021-04-14 16:53
@georgelouk are you saying you get this error from Tripal each time you've installed it? or you get errors like this with anything Drupal related?

**Comment by georgelouk** [comment] 2021-04-14 16:58
> @georgelouk are you saying you get this error from Tripal each time you've installed it? or you get errors like this with anything Drupal related?

This error appear anytime i enable "Tripal Chado Views" checkbox from modules section in Drupal. From that moment the error is appearing at any page i'm trying to access.

You can see it at : tripal.nut.gr

**Comment by spficklin** [comment] 2021-04-14 17:48
Okay, so I can recreate the error if I enable the `tripal_chado_views` module before enabling the `tripal_chado` module.  it seems we failed to list the `tripal_chado` module as a dependency of the `tripal_chado_views` module.  

Did you enable the `tripal_chado` module?

**Comment by georgelouk** [comment] 2021-04-14 18:00
I think no because tripal_chado has as a prerequisite module the tripal_chado_views.
I will recreate the installation to check it out, but i'm 99% sure that it is required first to enable the tripal_chado_views

**Comment by spficklin** [comment] 2021-04-14 18:14
Oh! I see that now. Yes, you're correct.  The `tripal_chado` module is listing the `tripal_chado_views` module as a dependnecy! I don't think that's correct. I'm amazed this hasn't been noticed until now.  But I suspect it's because most folks follow the command-line instructions for installation. If you follow these instructions step-by-step the problem doesn't occur:  https://tripal.readthedocs.io/en/latest/user_guide/install_tripal/manual_install/install_tripal.html.

Thanks for posting this. We can get it fixed. But let me ping @laceysanderson to make sure there wasn't some reason we had that setup that way, but I can't think of what it would be.

**Comment by georgelouk** [comment] 2021-04-14 19:01
Thanks for checking that out, i will wait for an update.
Unfortunately for various reasons i can't right now use the command line guide, so i 've tried with the durpal/gui instructions.

**Comment by spficklin** [comment] 2021-04-14 19:05
I understand.  I'm just waiting to hear from @laceysanderson to make sure I'm not missing something and then I think we can turn around a quick fix. It will mean, though, that you'll need to use the development version until we get the 3.6 release out (which should be in the next few weeks).   

I don't think we've ever had a user that couldn't use the command-line. I suppose you may have other issues. If you do, let us know and we can try help.

**Comment by spficklin** [comment] 2021-04-14 22:00
@georgelouk .  So it seems we have built in an inter-dependency between those two modules that's not easily fixed.  However, you can get around this problem if you enable the `tripal_chado` module without first enabling the `tripal_chado_views` module.  It's backwards but it works.   I just tested it and did not get the error this time.  After chatting with @laceysanderson I don't think we can change it. We're actively working on Tripal v4 for Drupal 8/9 and we'll be sure to address this issue in that version.

So, give it a try with the GUI and let me know if that works for you.

**Comment by georgelouk** [comment] 2021-04-15 07:28
@spficklin Sounds fare, but how can i achieve that? Will i enable tripal_chado directly from the database before i enable tripal_chado_views?

**Comment by spficklin** [comment] 2021-04-15 16:18
You should be able to enable Tripal Chado using the Drupal interface. In the screenshot below I am able to enable Tripal Chado even though it does indicates that Tripal Chado Views is a dependency.

![image](https://user-images.githubusercontent.com/1719352/114903328-8cbc3a80-9dcb-11eb-8792-5fedde1e7627.png)

**Comment by spficklin** [comment] 2021-04-19 18:16
Hi @georgelouk . I'm following up with this. Did you get around the problem?

**Comment by georgelouk** [comment] 2021-04-21 10:54
Hi @spficklin,

Yes, after i enabled tripal_chado first then those errors disappeared.
Now i've stuck to the next steps but regarding this bug, it worked the way you suggested.

**Comment by spficklin** [comment] 2021-04-21 15:18
Okay, great. I'm closing this out then.  Thanks.

**Closed as completed by spficklin** 2021-04-21 15:18 UTC
Labels: bug - confirmed, waiting on submitter
