### ISSUE TITLE
chado_query array[] placeholder does not work as intended

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#1272] opened 2022-04-25 16:41 UTC
This issue was found while testing the GFF3 loader. Basically the GFF3 loader in some of it's functions sends an array containing values to th chado_query function. This is particularly noted for features. This causes an undesired error.

Example 
$array = [
   'value1',
   'value2'
]

chado_query('SELECT * FROM features WHERE feature_id IN(:array[])', array(
  ':array[]' => $array
));

To avoid this issue at the moment, the code has been converted to create a placeholder for each value instead of using the array[].

**Comment by spficklin** [comment] 2022-04-25 16:47
Toa clarify, this problem is buried in the `chado_query` function.  With Drupal 9 it is now required, as @risharde points out above, to specify square brackets in placeholders that have arrays.   

See details here:  https://www.drupal.org/docs/drupal-apis/database-api/static-queries#placeholder-arrays

The problem is that in Tripal 3 we added the construct to a query of surrounding Drupal tables with square brackets if we wanted to do a cross schema join.  If you follow Drupal 9 coding style our regular expression for finding brackets now breaks.  Here are the two places where it breaks:

https://github.com/tripal/t4d8/blob/9587d71bd4cdb9bf9b1d83d086da5c0befccf1eb/tripal_chado/src/api/tripal_chado.query.api.inc#L1823-L1825

https://github.com/tripal/t4d8/blob/9587d71bd4cdb9bf9b1d83d086da5c0befccf1eb/tripal_chado/src/api/tripal_chado.query.api.inc#L1866-L1875

So, this isn't a problem just with the GFF3 loader. It's a problem for any SQL statement that is passed to `chado_query` that needs to use a list of values in a placeholder.

**Comment by dsenalik** [comment] 2022-10-30 14:54
I looked at this issue and to me the fix could be quite simple, simply change the two regular expressions substituting ```+``` for ```*``` and now ```[]``` will not match

Testing:
To test I put this code in the devel module php window
```
$sql = "select * from [bogus] where xyzzy=:somestuff[]";
print ">>>Regex1 Before\n";
preg_match_all('/\[(.*?)\]/', $sql, $matches);
var_dump($matches);
print ">>>Regex1 After\n";
preg_match_all('/\[(.+?)\]/', $sql, $matches);
var_dump($matches);
print ">>>Regex2 Before\n";
preg_match_all('/\[(\w*?)\]/', $sql, $matches);
var_dump($matches);
print ">>>Regex2 After\n";
preg_match_all('/\[(\w+?)\]/', $sql, $matches);
var_dump($matches);
```

and get this output
```
>>>Regex1 Before
array(2) {
  [0]=>
  array(2) {
    [0]=>
    string(7) "[bogus]"
    [1]=>
    string(2) "[]"
  }
  [1]=>
  array(2) {
    [0]=>
    string(5) "bogus"
    [1]=>
    string(0) ""
  }
}
>>>Regex1 After
array(2) {
  [0]=>
  array(1) {
    [0]=>
    string(7) "[bogus]"
  }
  [1]=>
  array(1) {
    [0]=>
    string(5) "bogus"
  }
}
>>>Regex2 Before
array(2) {
  [0]=>
  array(2) {
    [0]=>
    string(7) "[bogus]"
    [1]=>
    string(2) "[]"
  }
  [1]=>
  array(2) {
    [0]=>
    string(5) "bogus"
    [1]=>
    string(0) ""
  }
}
>>>Regex2 After
array(2) {
  [0]=>
  array(1) {
    [0]=>
    string(7) "[bogus]"
  }
  [1]=>
  array(1) {
    [0]=>
    string(5) "bogus"
  }
}
```

**Comment by dsenalik** [comment] 2022-10-31 15:07
I commented in the pull request why this is not enough, an underlying drupal 7 regex won't allow the square brackets through.

**Comment by dsenalik** [comment] 2022-11-21 16:44
I am closing this issue as **wontfix** because of the underlying drupal 7 issue that makes this impossible to do. This is because the drupal function ```expandArguments(&$query, &$args)``` around line 816 of ```database/database.inc``` uses a regex that is not compatible with this scheme. See the linked pull request (now closed) for more details.

**Closed as completed by dsenalik** 2022-11-21 16:44 UTC
Labels: wontfix, bug - external
