### ISSUE TITLE
Bundle creation permission error due to admin username

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#562] opened 2018-08-20 13:40 UTC
### System information

* Tripal Version: 7.x-3.x
* Drupal Version: 7.59
* PostgreSQL Version: 9.6
* PHP Version: 7.1

### Issue description

Creating a tripal content type for `Library` results in an error on our site. We used the term [nucleic acid library](https://www.ebi.ac.uk/ols/ontologies/ero/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FERO_0000160) to create the bundle.

#### Steps to reproduce

- Create a new content type
- Use the term: [nucleic acid library](https://www.ebi.ac.uk/ols/ontologies/ero/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FERO_0000160)
- If the term doesn't exist in your DB, insert it first.
- Choose library as the chado table
- Submit without changing the type_id column

#### Error messages and screenshots

```
PDOException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "" LINE 4: WHERE ( (rid = '') AND (permission = 'create bio_data_27') ) ^: SELECT 1 AS expression FROM {role_permission} role_permission WHERE ( (rid = :db_condition_placeholder_0) AND (permission = :db_condition_placeholder_1) ); Array ( [:db_condition_placeholder_0] => [:db_condition_placeholder_1] => create bio_data_27 ) in user_role_grant_permissions() (line 3174 of /home/www/modules/user/user.module).
```

<img width="582" alt="screen shot 2018-08-20 at 9 39 11 am" src="https://user-images.githubusercontent.com/1512664/44343803-ecb48480-a45c-11e8-840f-2233601d20e1.png">

### Notes

The content got actually created and seems to function properly even though the error above showed up. It seems as if tripal simply failed to edit the permissions for the content type but didn't fail anywhere else.

**Comment by spficklin** [comment] 2018-08-21 06:03
I am not able to recreate this problem. I added the "nucleic acid library" term to my database, created the type using the chado.library table (with type_id differentiating the type) and it created just fine.  

I think though, that the problem may be caused by these lines of code:

https://github.com/tripal/tripal/blob/85b3c2988e5ebc8083c67b34ed8fa1ef7efd253e/tripal/includes/TripalBundleUIController.inc#L882-L895

This code is called in the hook_admin_access function.  We have added to the bottom of that function code which is meant to automatically turn on the permission for the admin user, but since the admin user is hard-coded as 'administrator' I suspect your admin account is not named 'administrator'.  I'll add a fix that will get around this.

**Comment by spficklin** [comment] 2018-08-21 18:36
@almasaeed2010 since the PR did not fix the problem for you.   Would you mind running this code and letting me know if it returns the name of the administrator role on your site?

```
drush php-eval "print(variable_get('user_admin_role'));"
```

**Comment by almasaeed2010** [comment] 2018-08-21 18:37
Hi @spficklin 

the command returns `0`:

```bash
drush php-eval "print(variable_get('user_admin_role'));"
0
```

Thanks!

**Comment by almasaeed2010** [comment] 2018-08-21 18:47
I found this code snippet that returns the current name for the role in case it's useful:

```php
user_roles(false, 'administer tripal');
// Returns array(3 => 'admins')
```

Running 
```bash
drush php-eval "print current(user_roles(false, 'administer tripal'));"
```
returns the correct admin user role as specified in our site:
```bash
admins
```

**Comment by spficklin** [comment] 2018-08-23 17:53
Fix has been applied via the PR.

**Closed as completed** 2018-08-23 17:52 UTC
Labels: bug - confirmed, Priority - Release Blocker
