### ISSUE TITLE
TripalField namespace issue

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#141] opened 2017-08-02 15:11 UTC
If two TripalField classes have the same name there will be a scope problem. Morever, if two fields use the same term there will be potential problems as well.

**Comment by laceysanderson** [comment] 2017-08-02 16:37
The issue where two fields have the same term is actually quite a big one. For example, I had used rdfs:type in my property table to indicate the genetic marker type (e.g. Exome Capture). In this situation Tripal simply didn't create a property field displaying that data. There was no warning/error anywhere that I could see. At the very least we need to add some warnings :-)

**Comment by almasaeed2010** [comment] 2017-09-14 14:09
We've also encountered the same issue trying to create multiple `schema:description` fields for the `chado.protocol` bundle. The table has 3 description fields, `softwaredescription`, `hardwaredescription` and `protocoldescription`. The properties didn't show up on the bundle manage fields page and Tripal did not issue any warning. Further, it looks like Tripal creates the machine name of the field based on the cv term. Would it make sense to allow machine names to be specified by the developer in the tripal_create_bundle function?

Alternatively, tripal_create_bundle could perform additional checks to make sure all machine names it is creating are unique to the bundle.

Please let us know if we can help getting this functioning properly.

Thanks!

**Comment by spficklin** [comment] 2017-09-27 17:20
Hi @almasaeed2010 

In the case of the chado.protocol table I would recommend against using the 'schema:description' term for all three of those columns even if they are all descriptions.  The reason is that the 'schema:description' term is too generic for what data those columns contain.  I don't think it makes sense for an entity to have multiple fields with the same term.  If the same term is used then all values belonging to that term should then be provided in an array of values under a single field.  Make sense?  In that sense, you could combine all three of those description columns as an array of values, or concatenate them.  But, I would recommend you find or create a term for each column separately and that will solve the naming problem, and it informs the end-user better about the meaning of the columns.   

If you do find appropriate terms for each column of the chado.protocol table please let us know and we can see if they would make sense to incorporate into Tripal itself.

**Comment by almasaeed2010** [comment] 2017-09-27 17:30
Thanks @spficklin. This totally makes sense.
We did end up using more specific terms for each field but they are `local` terms. Searching through NCBI didn't yield anything that we thought was appropriate, unfortunately.

Thanks!

**Comment by spficklin** [comment] 2017-09-27 18:40
If you don't mind me asking, what were the terms you came up with?

**Comment by almasaeed2010** [comment] 2017-09-27 18:42
They were very straight forward:
```
local:protocol_description
local:software_description
local:hardware_description
```

**Comment by spficklin** [comment] 2017-10-21 00:06
To add to this, can you share the description you used for each of these as well?

**Comment by spficklin** [comment] 2018-05-25 08:27
I think I may have come up with an okay solution for both problem cases described here:

1)  For the issue described by @laceysanderson I have added some code that prints an error message on the Tripal content type page if two or more fields have the same term. It instructs the user to only use a term once and to correct the problem.  I could not duplicate the issue with a property not being created if the term is already in used.  I'm guessing that may have been non-related and fixed in a previous commit.  I will issue a pull request with this fix.

2)  For the issue described by @almasaeed2010. Unfortunately, if two fields have the same machine name programmatically then it's not easy to distinguish between them.  This is because the info array returned by the hook_bundle_field_info and hook_bundle_instance_info functions get called multiple times and fields/instances that already exist are skipped and new ones added.  However, in answer to your question, it is possible to set a different machine name. The machine name should be the same as the 'field_name' element of the info arrays.   You probably figured that out already.

**Comment by laceysanderson** [comment] 2018-05-26 16:29
The PR #388 did not fix my problem :-( Specifically, I did not see any errors/warnings in the Drupal watchdog logs, the apache error log or on the manage fields page. Luckily I also didn't end up with two rdfs__type fields ;-)

Steps to Reproduce:
1. Insert an organismprop of type `rdfs:type` using 
```sql
INSERT INTO chado.organismprop (organism_id, type_id, value) 
SELECT 1 as organism_id, cvt.cvterm_id as type_id, 'Testing this out #141' as value 
FROM chado.cvterm cvt 
LEFT JOIN chado.cv ON cv.cv_id=cvt.cv_id 
WHERE cv.name='rdfs' AND cvt.name='type';
```
2. Navigate to the organism manage fields page at `[your tripal site]/admin/structure/bio_data/manage/[machine name for organism entity]/fields`.
3. Clear the cache repetitively, click check fields multiple times in various combinations.
4. Note that you have no new field of type `Chado Property` with name `rdfs__type`. Also note that you have no warning in any of the logs.

**Comment by bradfordcondon** [comment] 2018-05-29 15:06
i find this issue kind of interesting.  The[ CV-xray](https://github.com/statonlab/tripal_cv_xray) field creates a new instance for each Ontology/feature type you want.  So if I want the KEGG and GO browsers enabled on organism, I make two fields.  But they can't use the same term (I use `data:4231`)?  So I would have to instruct users to change the term of one of the fields when creating.
Did I approach this wrong?  Should you instead set the cardinality of the field instead of allowing people to attach multiple?

**Comment by laceysanderson** [comment] 2018-05-29 18:23
For the Tripal Fancy Field summary charts, I set the term to NULL so that when users create it through the UI they have to assign their own CVterm.

I think your approach is perfect and that your users should change/set the term. In your example, KEGG and GO browsers are different and thus should have different, more specific terms -don't you think?

**Comment by bradfordcondon** [comment] 2018-05-29 18:34
but theres no world where a specific cvterm exists, because its a combination of the entity type (say, mRNA), and the ontology.  therefore only the generic term makes sense (data:ontological data)....

So as an example, say i've got tWO GO mappings: one for biomaterials and one for mRNA.  


In all these cases you have to use a local term which is something I try to avoid, perhaps too much...

**Comment by spficklin** [comment] 2018-06-16 07:09
I have submitted a PR #445 which provides more robust warnings and form validation errors if a term namespace problem occurs.

**Comment by laceysanderson** [comment] 2018-06-21 03:12
Closing as we now have good warnings for all the cases we can think of surrounding this.

**Closed as completed by laceysanderson** 2018-06-21 03:12 UTC
Labels: bug - confirmed, Priority - Release Blocker
