### ISSUE TITLE
tripal_cv_load_obo_v1_2() function not available in legacy mode

### ISSUE THREAD

**Issue by guignonv** [tripal/tripal#821] opened 2019-01-10 18:14 UTC
Tripal Version: 3.x (head)
Drupal Version: 7
PostgreSQL Version: not relevant
PHP Version: not relevant

Function tripal_cv_load_obo_v1_2() was available in Tripal 2 but is not present in Tripal 3 legacy mode.

**Comment by laceysanderson** [comment] 2019-01-10 21:27
The problem is due to the fact that the legacy obo loader was removed when the new one was created... We got around it by upgrading the module to check/default to the new obo loader if it's available.

That said, this does break backwards compatibility of extension modules in Tripal 3 legacy mode.

**Comment by bradfordcondon** [comment] 2019-02-05 14:29
i think `tripal_cv_load_obo_v1_2` can just wrap the new tripal 3 loader, right?  That's the solution I would propose if you need that function.

**Comment by guignonv** [comment] 2019-02-06 15:39
I think we try (during the codefest at PAG2019) to use the v3 loader but it does not work like the `tripal_cv_load_obo_v1_2` does. And I think I remember Lacey saying the new version is more restrictive (@laceysanderson can you confirm?). So maybe the idea might be to grab the old obo lodaer version and put it in a legacy module? :-s I don't know.

**Comment by bradfordcondon** [comment] 2019-02-06 16:24
if the new loader wont work, then this is the same problem I have currently for tripal_analysis_kegg, where i have a custom OBO that no longer meets the standards the new OBO loader requires: https://github.com/tripal/tripal_analysis_kegg/issues/18

The answer there was "fix the OBO".  i think to move this discussion forward we would need you to link the OBO that wont work with the new loader and we can see what error messages you get with it.

It might be really nice for both of us to include a legacy loader as an option for these problematic but helpful OBOs.

**Comment by guignonv** [comment] 2019-02-06 17:25
Don't worry about the OBO, it has been fixed already. :)

**Comment by spficklin** [comment] 2019-02-06 17:30
Hi Folks, I thought @shawnawsu and I made sure that the OBO loader was backwards compatible. The same function names should have been used. IF it is not then we have a problem.  Can someone provide details about what's different?

@guignonv you said this above:

> "I think we try (during the codefest at PAG2019) to use the v3 loader but it does not work like the `tripal_cv_load_obo_v1_2` does. And I think I remember Lacey saying the new version is more restrictive (@laceysanderson can you confirm?)."

The new OBO loader should not be more restrictive, it should actually handle the OBO correctly now, especially at OBOs are increasingly borrowing terms from one another.  The old Tv2 loader no longer works with the newest ontologies, and it should not be more restrictive, it should load the OBO's as is. Can you give more details on what the challenges you have with it?

**Comment by bradfordcondon** [comment] 2019-02-06 17:45
`tripal_cv_load_obo_v1_2` is not in the code base anymore.  see:  https://github.com/tripal/tripal/search?q=tripal_cv_load_obo_v1_2&unscoped_q=tripal_cv_load_obo_v1_2
So thats was my suggestion to implement this function, but creating a OBOImporter class and running it.

edit: I'm also just assuming that said function ever existed :D

**Comment by spficklin** [comment] 2019-02-06 18:35
oops... clicked the wrong button

**Comment by laceysanderson** [comment] 2019-02-06 20:42
The related issues are https://github.com/tripal/brapi/issues/7 and https://github.com/tripal/brapi/issues/6. The `tripal_cv_load_obo_v1_2` function existed in Tripal 2 but not in much of Tripal 3. To get around this we ended up only using the new obo loader when in legacy mode and fixing the OBO to work with it.

**Comment by spficklin** [comment] 2019-02-06 22:54
Oh, right, we moved all of that code into the OBO loader.  Now I remember.  Thanks, Lacey.  So, I was wrong we wouldn't have tried to make that backward's compatible because those functions were part of the loader and not part of the API.   

I think your solution is just fine.

**Comment by laceysanderson** [comment] 2019-03-20 21:44
Since we have a solution and `tripal_cv_load_obo_v1_2` is not an API function and thus doesn't need to be backwards compatible... I'm going to close this issue. Comment if you disagree.

**Closed as completed by laceysanderson** 2019-03-20 21:44 UTC
