### ISSUE TITLE
Dashboard on a newly created Tripal3 site gives PHP Warning related to tripal_daemon

### ISSUE THREAD

**Issue by carolyncaron** [tripal/tripal#338] opened 2018-04-13 22:28 UTC
### System information

* Tripal Version: 7.x-3.x commit a98e03f0e4b357c67d8b44b7b5c4ce75cac1cf51
* Drupal Version: 7.55
* PostgreSQL Version: 9.3.15
* PHP Version: 5.5.9

### Issue description

I've created a brand new Tripal 3 site on which to develop an extension module, and noticed the following PHP error at the top of the "Dashboard" page. I have not yet started the daemon, only created an organism and installed/enabled my module.

> PHP Warning: file_get_contents(): Filename cannot be empty in /home/ubuntu/workspace/sites/all/modules/tripal/tripal_daemon/includes/tripal_daemon.blocks.inc on line 158 pid 16923 PHP Warning: file_get_contents(): Filename cannot be empty in /home/ubuntu/workspace/sites/all/modules/tripal/tripal_daemon/includes/tripal_daemon.blocks.inc on line 73 pid 16923 PHP Notice: Undefined index: attributes in /home/ubuntu/workspace/includes/theme.inc on line 1878 pid 16923 PHP Warning: Invalid argument supplied for foreach() in /home/ubuntu/workspace/sites/all/modules/tripal/tripal_daemon/includes/tripal_daemon.blocks.inc on line 115 pid 16923

**Comment by spficklin** [comment] 2018-05-25 07:36
I am not able to duplicate these errors, but I am also not able to see any logs from the daemon on the dashboard either.  @carolyncaron are you still experiencing this?

**Comment by laceysanderson** [comment] 2018-05-26 20:02
I can confirm on a clean install.
![screen shot 2018-05-26 at 2 01 40 pm](https://user-images.githubusercontent.com/1566301/40579801-6038683a-60ed-11e8-852c-307d69dd9d5c.png)

Stephen, do you have the modules/tripal/tripal_daemon enabled and modules/tripal_daemon removed?

**Comment by spficklin** [comment] 2018-05-29 20:27
Hi @laceysanderson .  I only had the tripal_daemon from tripal v3 enabled (not the separate extension module).

**Comment by laceysanderson** [comment] 2018-05-29 21:39
Interesting @spficklin... Do you see the daemon blocks now?

**Comment by spficklin** [comment] 2018-05-30 21:53
Yes, I see the block, just not any logs.

**Comment by laceysanderson** [comment] 2018-05-30 22:26
Interesting... maybe you should file that as an independent issue? I can't duplicate it except when there are no logs to display of course. Even then I see the logs block.

Anyway, marking this as closed since the original problem is fixed via PR.

**Closed as completed by laceysanderson** 2018-05-30 22:26 UTC
Labels: bug - confirmed, Priority - Release Blocker
