### ISSUE TITLE
Cannot access type_id field in Contacts

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#234] opened 2017-12-18 17:18 UTC
Trying to filter chado table 'contacts'  by 'type_id' via Views
However, there is no type_id in the Tripal Content Type 'Contact' that returns the relevant data which is usually Person or Organization and therefore no filter on the Views side to do filtering either.
The Contact Tripal Content Type doesn't have any field 'type_id', is this also a bug?

**Comment by spficklin** [comment] 2017-12-19 03:04
@risharde I have pushed a fix to the development branch that should fix this problem for you.  There was a bug in that this field wasn't being added.   To get the type field to show up you will need to do the following:

1)  Update the code to the most recent development verison
2)  Go to Admin > Structure > Tripal Content Types  and click 'manage fields' for the Contact content type.
3)  Click the link at the top of the page that reads 'Check for new fields'.  This will add the Contact Type field.

You should then be able to add that field in the View.  Let me know if this works for you.

**Comment by risharde** [comment] 2017-12-19 08:55
Great Stephen, thanks a lot, will test and let you know

**Comment by spficklin** [comment] 2017-12-20 18:50
Let me know if this works and we can close out the issue.  Thanks.

**Comment by shawnawsu** [comment] 2018-03-09 18:28
@risharde I am going to close this ticket. If the problem is not fixed please reopen it.

**Closed as completed by shawnawsu** 2018-03-09 18:28 UTC
Labels: bug - confirmed, waiting on submitter
