### ISSUE TITLE
Tripal 3 migrate: Delete node step spams warning

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#265] opened 2018-01-23 16:57 UTC
### System information

* Tripal Version: 3
* Drupal Version: 7 .57
* PostgreSQL Version: 9.3.2
* PHP Version: 7.0.26

### Issue description

I am currently running the final migration step: deleting tripal content nodes.  

The job is currently running.  At every content type the console is spammed with the following warning (1 per content type I would guess?  Enough that I can't scroll up to see anything else.)

````
strtr(): The second argument is not an array syslog.module:115                                                                  [warning]
```

**Comment by spficklin** [comment] 2018-01-24 08:18
That's the only message you get.... that strstr() error?

**Comment by bradfordcondon** [comment] 2018-01-24 12:08
I'm rerunning today (the job failed because of losing connection to db) and will properly log the console this time:  there were so many they washed away any other errors.

**Comment by chunhuaicheng** [comment] 2018-01-24 12:43
A bug was introduced when the Tripal Job API got changed. I've committed a fix. Can you pull and see if you still get the same error?

**Comment by bradfordcondon** [comment] 2018-01-24 13:45
no change. My previous job had almost finished, so i only had two content types left:  here's the full console output.


```

NOTE: This operation is performed using a database transaction.
If it fails or is terminated prematurely then the entire set of
changes is rolled back and will not be found in the database

Verifying chado_library records...

Deleted 0 record(s) from chado_library missing either a node or chado entry.
Verifying nodes...
strtr(): The second argument is not an array syslog.module:115                                                                 [warning]
strtr(): The second argument is not an array syslog.module:115                                                                 [warning]
strtr(): The second argument is not an array syslog.module:115                                                                 [warning]
strtr(): The second argument is not an array syslog.module:115                                                                 [warning]
strtr(): The second argument is not an array syslog.module:115                                                                 [warning]
strtr(): The second argument is not an array syslog.module:115                                                                 [warning]
strtr(): The second argument is not an array syslog.module:115                                                                 [warning]
strtr(): The second argument is not an array syslog.module:115                                                                 [warning]
strtr(): The second argument is not an array syslog.module:115                                                                 [warning]
strtr(): The second argument is not an array syslog.module:115                                                                 [warning]
strtr(): The second argument is not an array syslog.module:115                                                                 [warning]
strtr(): The second argument is not an array syslog.module:115                                                                 [warning]
strtr(): The second argument is not an array syslog.module:115                                                                 [warning]
strtr(): The second argument is not an array syslog.module:115                                                                 [warning]
strtr(): The second argument is not an array syslog.module:115                                                                 [warning]
strtr(): The second argument is not an array syslog.module:115                                                                 [warning]
strtr(): The second argument is not an array syslog.module:115                                                                 [warning]
strtr(): The second argument is not an array syslog.module:115                                                                 [warning]
strtr(): The second argument is not an array syslog.module:115                                                                 [warning]
strtr(): The second argument is not an array syslog.module:115                                                                 [warning]
strtr(): The second argument is not an array syslog.module:115                                                                 [warning]
Percent complete: 100.00%. Memory: 54,586,456 bytes.
Deleted 21 node(s) that did not have corresponding chado_library entries.

NOTE: This operation is performed using a database transaction.
If it fails or is terminated prematurely then the entire set of
changes is rolled back and will not be found in the database

Verifying chado_pub records...

Deleted 0 record(s) from chado_pub missing either a node or chado entry.
Verifying nodes...
strtr(): The second argument is not an array syslog.module:115                                                                 [warning]
Percent complete: 100.00%. Memory: 54,611,168 bytes.
Deleted 1 node(s) that did not have corresponding chado_pub entries.
```

**Comment by chunhuaicheng** [comment] 2018-01-25 14:09
hmm... I cannot reproduce this bug. The migration simply calls the 'chado_cleanup_orphaned_nodes()' API function to delete nodes and I didn't get any strtr() warning.

**Comment by bradfordcondon** [comment] 2018-01-30 13:40
It's now clear to me that the cleanup_orphaned_nodes did not run for any of our content, as our site is full of orphaned nodes [like this one](http://160.36.205.61:8095/feature_old/QlobV1.0_scaffold12071_0000210-RA)

We'll see if we can get the cleanup to run and report back.

**Comment by almasaeed2010** [comment] 2018-01-30 21:11
Just an update on this. We managed to delete the remaining "orphaned" nodes and clear their aliases manually. Apparently, `chado_cleanup_orphaned_nodes()` worked for everything except `chado_feature` and all analyses `chado_analysis_blast` etc.

Thanks!

**Comment by laceysanderson** [comment] 2018-05-30 23:08
Marking this as resolved due to @almasaeed2010 response. If it's not, please re-open!

**Closed as completed by laceysanderson** 2018-05-30 23:08 UTC
Labels: bug - confirmed
