### ISSUE TITLE
Chado fields widget to hold multiple values?

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#240] opened 2017-12-28 18:51 UTC
Hi guys, so it seems Chado fields show up as text fields on edit or create forms. This however poses a challenge because sometimes we want multiple values in a field. Can chado field be extended to cater for such a situation?

**Comment by bradfordcondon** [comment] 2018-01-03 15:32
Short answer is yes.  Below is the Analysis content type, with the Cross reference, Annotations, and publication fields, all of which allow multiple values.

![screen shot 2018-01-03 at 10 31 07 am](https://user-images.githubusercontent.com/7063154/34526679-3956d4aa-f071-11e7-829d-652fc697a8d9.png)

**Comment by risharde** [comment] 2018-01-06 01:11
Hey @bradfordcondon, thanks for the response, do you know how to enable a field to be multifield? I know you answered yes, trying to determine if there is a procedure to do this, could you advise me on this?

**Comment by bradfordcondon** [comment] 2018-01-06 17:27
It is going to depend on the field.  If the field maps to a column in Chado (which is the case with many default fields), then it cannot be multifield (because theres just a single column).  The fields I showed you all go through a linker table in Chado and therefore allow multiple values.  Chado property fields also allow multiple values: if you want to define a field using the GUI, this is the route you want to take. 

 To define a chado property field, select Chado Property for field type.  Give the field a name and click save.
<img width="1200" alt="screen shot 2018-01-06 at 12 23 12 pm" src="https://user-images.githubusercontent.com/7063154/34642181-d8d98abe-f2dc-11e7-9bcd-ecdf709fc685.png">


You will then be prompted to set the field settings.  You must assign this field a vocabulary term: if a suitable one isn't in the database, you'll have to insert one first.  (dont mind the silly cvterm i've picked here)
<img width="707" alt="screen shot 2018-01-06 at 12 24 47 pm" src="https://user-images.githubusercontent.com/7063154/34642177-ccf83394-f2dc-11e7-9156-3d924844a6f0.png">


After saving the settings, your field will show up with the chado properties widget (when creating a new entity of that type), with an "Add another item" button which will allow you to set multiple properties for each entry.

<img width="502" alt="screen shot 2018-01-06 at 12 25 29 pm" src="https://user-images.githubusercontent.com/7063154/34642178-d03edc10-f2dc-11e7-8971-de32d5ceb813.png">

**Comment by spficklin** [comment] 2018-01-08 18:32
Hi @risharde can you tell us what Chado field you are hoping to display as a non-text field?

**Comment by risharde** [comment] 2018-01-08 21:18
Hey @spficklin  and @bradfordcondon , thank you for your assistance with the issue. I was able to get multi field going partially for the chado field which is research topics and also genus. It seems that for some reason, these fields were drupal fields as opposed to chado fields which caused it to show up as single text boxes. Now that I've go to the point of seeing the add 'Add another item' button for these fields, I get an AJAX error so I cannot add additional items. Stephen if you could please refer to bio_data/add/8 you will see the issue, please let me know if you have any ideas, a bit stumped on this

**Comment by spficklin** [comment] 2018-01-11 03:32
Hi @risharde. My bio_data/add/8 may not be the same as yours so I can't test it.  Can you post a screenshot?

**Comment by risharde** [comment] 2018-01-11 06:30
![1-multifield-addanotheritem-error](https://user-images.githubusercontent.com/33866403/34811432-3b6df8b6-f677-11e7-9a78-40c7cf5289ed.png)

Here's the screenshot, it looks like the Add Another Item button tries to post to /ajax - I'm guessing it should be posting to something else though.

If you need further access, we could reset your password on the dev for you to have a deeper look?

Thanks

**Comment by spficklin** [comment] 2018-01-11 06:32
So, one more question.  Is this 'Research Interest' added as a "Chado Property" using the admin GUI?

**Comment by risharde** [comment] 2018-01-11 06:44
@spficklin Yes, correct

**Comment by risharde** [comment] 2018-01-22 21:52
Hi @spficklin , any update on this one? This is a bit crippling :(

**Comment by spficklin** [comment] 2018-01-22 22:15
Hi @risharde. Okay, I've tested adding a Chado Property field onto a Contact content type and I cannot reproduce the problem.   It is supposed to make an AJAX call because Drupal is wanting to add a new form element without reloading the page.  That ResponseText in the error message of your screenshot above is a bit odd.  I've not seen that before.  Can you check your Drupal recent logs and Apache server logs to see if there are any clues as to what is going on behind the scenes when that AJAX fails

**Comment by risharde** [comment] 2018-01-22 22:34
Hey @spficklin , thanks for the response, I've tested other AJAX related calls and they work fine such as the autocomplete fields but yes, the response is actually from Devel module. I also disabled Devel in hopes it was that but it seems the ajax call itself isn't outputting any data even when devel is off. Only posted here because I've exhausted every possible idea in the book and via the search engines.

**Comment by spficklin** [comment] 2018-01-22 23:53
How about your server logs?  Often you can find sources of problems there.  Also, Drupal "recent logs" can be helpful if it's a Drupal related problem.

**Comment by risharde** [comment] 2018-03-13 02:59
Just an update on the solution, I found out that while altering the form using a custom module, the add more items button uses AJAX which is incompatible with $form['no_cache'] = true;
Therefore, to avoid getting this issue, make sure that no modules or custom modules are hooking into the form and altering this variable. $form['no_cache'] should be set to false when utilizing AJAX callback.

**Closed as completed** 2018-03-26 19:19 UTC
Labels: Community - Please Contribute
