### ISSUE TITLE
tripal-7.x-3.0-beta3 failed at drush pm-enable tripal

### ISSUE THREAD

**Issue by NicHerndon** [tripal/tripal#30] opened 2017-02-16 20:05 UTC
Trying to install Tripal3 beta3 on CentOS 7 failed with following error.

# drush pm-enable tripal
The following extensions will be enabled: tripal, php
Do you really want to continue? (y/n): y
PHP Parse error:  syntax error, unexpected '.', expecting ',' or ';' in /var/www/html/sites/all/modules/tripal/tripal/includes/TripalFields/TripalField.inc on line 18
Drush command terminated abnormally due to an unrecoverable error.                                                          [error]
Error: syntax error, unexpected '.', expecting ',' or ';' in
/var/www/html/sites/all/modules/tripal/tripal/includes/TripalFields/TripalField.inc, line 18

**Comment by laceysanderson** [comment] 2017-02-16 22:43
@NicHerndon that appears to be a PHP syntax error which I would think is a system-independant error however I am not able to repeat it on Debian. Where did you get your Tripal3 beta3 from and are you using a clean Drupal site or upgrading a Tripal2 site? 

After setting up a clean drupal site, I used `drush pm-download tripal-7.x-3.0-beta3` which grabs the package from Drupal.org. Unfortunately I don't have a CentOS testing environment... Do you experience the error when you use that process?

**Comment by NicHerndon** [comment] 2017-02-16 23:18
Lacey,

Thank you for looking into this issue.

I followed the installation instructions at Tripal v3.x User's Guide (beta)<http://tripal.info/tutorials/v3.x>, and got to http://tripal.info/tutorials/v3.x/installation/tripal#toc-install-tripal--76bkilOc.

I installed this on a ‘fresh’ system (a virtual machine with nothing else on it).

Nic

On Feb 16, 2017, at 5:43 PM, Lacey-Anne Sanderson <notifications@github.com<mailto:notifications@github.com>> wrote:


@NicHerndon<https://github.com/NicHerndon> that appears to be a PHP syntax error which I would think is a system-independant error however I am not able to repeat it on Debian. Where did you get your Tripal3 beta3 from and are you using a clean Drupal site or upgrading a Tripal2 site?

After setting up a clean drupal site, I used drush pm-download tripal-7.x-3.0-beta3 which grabs the package from Drupal.org<http://Drupal.org>. Unfortunately I don't have a CentOS testing environment... Do you experience the error when you use that process?

**Comment by spficklin** [comment] 2017-02-18 01:40
Nic, what version of PHP are you using on your CentOS machine?  Here's that line of code that the error message above reports as causing problems for you:

```
  // The default description for this field.
  public static $default_description = 'The generic base class for all Tripal fields. ' .
    'Replace this text as appropriate for the child implementation.';
```
Note the period at the end means concatenation and the rest of the line wraps around.  That period seems to throw off your PHP. It seems to want a semicolon or comma.  I'm not sure why....

I'm using PHP version 7.0.8

**Comment by NicHerndon** [comment] 2017-02-18 01:48
$ php -v
PHP 5.4.16 (cli) (built: Nov  6 2016 00:29:02)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies

Let me try to update the PHP. I’ll keep you posted.

On Feb 17, 2017, at 8:40 PM, Stephen Ficklin <notifications@github.com<mailto:notifications@github.com>> wrote:


Nic, what version of PHP are you using on your CentOS machine? Here's that line of code that the error message above reports as causing problems for you:

  // The default description for this field.
  public static $default_description = 'The generic base class for all Tripal fields. ' .
    'Replace this text as appropriate for the child implementation.';


Note the period at the end means concatenation and the rest of the line wraps around. That period seems to throwing off your PHP. It seems to want a semicolon or comma. I'm not sure why....

I'm using PHP version 7.0.8

**Comment by NicHerndon** [comment] 2017-02-18 03:01
$ php -v
PHP 7.1.2 (cli) (built: Feb 15 2017 08:36:40) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

Upgrading PHP did the trick. Proceeding with Chado install now.

Thank you Stephen.

Nic

On Feb 17, 2017, at 8:40 PM, Stephen Ficklin <notifications@github.com<mailto:notifications@github.com>> wrote:


Nic, what version of PHP are you using on your CentOS machine? Here's that line of code that the error message above reports as causing problems for you:

  // The default description for this field.
  public static $default_description = 'The generic base class for all Tripal fields. ' .
    'Replace this text as appropriate for the child implementation.';


Note the period at the end means concatenation and the rest of the line wraps around. That period seems to throwing off your PHP. It seems to want a semicolon or comma. I'm not sure why....

I'm using PHP version 7.0.8

**Comment by spficklin** [comment] 2017-02-18 15:16
What version of PHP did you have before you upgraded?  I want to update the tutorial to instruct folks on CentOS to update PHP.  Do you have the commands you used to update PHP on CentOS?

Thanks

**Comment by mdondrup** [comment] 2017-02-18 15:39
Hi Stephen,

could you indicate the minimal version requirement for PHP in Tripal 3. The standard version of CentOS 6 is
still PHP 5.3.3 for example, I am not sure PHP 7 is available even in CentOS 7 repos. External
repos like webtatic.com or EPEL could be a way.

Michael

**Comment by NicHerndon** [comment] 2017-02-19 00:41
Stephen,

I upgraded from 5.4.16 to 7.1.2. I followed the instructions at https://rpms.remirepo.net/wizard/.

Nic

On Feb 18, 2017, at 10:16 AM, Stephen Ficklin <notifications@github.com<mailto:notifications@github.com>> wrote:


What version of PHP did you have before you upgraded? I want to update the tutorial to instruct folks on CentOS to update PHP. Do you have the commands you used to update PHP on CentOS?

Thanks

**Comment by NicHerndon** [comment] 2017-02-19 00:50
I continued with the installation and got another error at Prepare Chado and Drupal (http://tripal.info/tutorials/v3.x/installation/tripal#toc-prepare-chado-and-drupal-cOni2qZc).

I installed Chado.

[root@localhost html]# drush trp-run-jobs --username=drupal --root=/var/www/html
Tripal Job Launcher
Running as user 'drupal'
-------------------
Calling: tripal_chado_install_chado(Install Chado v1.3, 3)
Creating 'chado' schema
Loading sites/all/modules/tripal/tripal_chado/chado_schema/default_schema-1.3.sql...
Install of Chado v1.3 (Step 1 of 2) Successful!
Loading sites/all/modules/tripal/tripal_chado/chado_schema/initialize-1.3.sql...
Install of Chado v1.3 (Step 2 of 2) Successful.
Installation Complete

But failed at Chado and Drupal prepare:

[root@localhost html]# drush trp-run-jobs --username=drupal --root=/var/www/html
Tripal Job Launcher
Running as user 'drupal'
-------------------
Calling: tripal_chado_prepare_chado(a:0:{}, 4)
WD php: Error: [] operator not supported for strings in              [error]
chado_select_record() (line 1331 of
/var/www/html/sites/all/modules/tripal/tripal_chado/api/tripal_chado.query.api.inc).
Cannot modify header information - headers already sent by (output   [warning]
started at /usr/share/drush/includes/output.inc:41)
bootstrap.inc:1481
Error: [] operator not supported for strings in chado_select_record() (line 1331 of /var/www/html/sites/all/modules/tripal/tripal_chado/api/tripal_chado.query.api.inc).
Drush command terminated abnormally due to an unrecoverable error.   [error]

On Feb 18, 2017, at 10:16 AM, Stephen Ficklin <notifications@github.com<mailto:notifications@github.com>> wrote:


What version of PHP did you have before you upgraded? I want to update the tutorial to instruct folks on CentOS to update PHP. Do you have the commands you used to update PHP on CentOS?

Thanks

**Comment by spficklin** [comment] 2017-03-07 18:19
Hi @NicHerndon. It's been a few weeks since you posted.  I'm catching up on issues.  I'm not able to duplicate this problem.  Are you still experiencing this?

**Comment by spficklin** [comment] 2017-03-14 18:42
Closing this out as there's not been input recently. Please reopen if the issue is still present.

**Closed as completed by spficklin** 2017-03-14 18:42 UTC
