### ISSUE TITLE
After update: Could not find details about the vocabulary: SOFP.

### ISSUE THREAD

**Issue by mdondrup** [tripal/tripal#892] opened 2019-03-15 09:14 UTC
### System information

* Tripal Version: 7.x-3.1
* Drupal Version: 7.61
* PostgreSQL Version: 10.3
* PHP Version: 7.1

### Issue description

After updating from Tripal 2.1 to Tripal 3.1, I get a lot of warnings about missing ontology SOFP. I searched the documentation, the code and google, but the only mention is on the demo.tripal.org site and in 3 files on git: https://github.com/tripal/tripal/search?q=SOFP&unscoped_q=SOFP 

Tried re-populating the mview to no avail. The database does not contain an ontology with that name either.

#### Steps to reproduce
Sorry, no clue ;)

#### Error messages and screenshots

```
Could not find details about the vocabulary: SOFP. Note: if this vocabulary does exist, try re-populating the db2cv_mview materialized view at Admin > Tripal > Data Storage > Chado > Materialized views.
```

**Comment by bradfordcondon** [comment] 2019-03-15 13:16
hi @mdondrup I  have seen this on another site.

These are the SOFP terms I had on the site:

```
select DISTINCT cv.name, cvt.name from chado.cv cv INNER JOIN chado.cvterm cvt ON cvt.cv_id = cv.cv_id where cvt.dbxref_id in (SELECT dbx.dbxref_id from chado.dbxref dbx where dbx.db_id = 43);
name	name
feature_property	sp_comment
feature_property	protein_id
feature_property	validation_flag
feature_property	qseq_type
feature_property	score
feature_property	status
feature_property	missing_start_codon
feature_property	citation
feature_property	dev_stage
feature_property	reported_pr_change
feature_property	keywords
feature_property	problem
feature_property	na_change
feature_property	date
feature_property	cyto_range
feature_property	evidenceGB
feature_property	missing_stop_codon
feature_property	synonym
feature_property	anticodon
feature_property	chromosome
feature_property	comment
feature_property	readthrough_stop_codon
feature_property	unixdate
feature_property	finished
feature_property	pr_change
feature_property	ontology_term
feature_property	linked_to
feature_property	map
feature_property	reported_na_change
feature_property	mol_type
feature_property	source
feature_property	description
feature_property	sp_status
feature_property	feature_property
feature_property	Gap
feature_property	encoded_symbol
feature_property	symbol
feature_property	orf_classification
feature_property	organism
feature_property	owner
feature_property	internal_synonym
feature_property	gbunit
feature_property	dicistronic
feature_property	element
feature_property	non_canonical_start_codon
feature_property	Note
feature_property	aminoacid
(47 rows)
```

I thought that maybe these were old Sequence Ontology terms (Sequence ontology Feature Property) I could find some of them for example [`non_canonical_start_codon`](https://www.ebi.ac.uk/ols/search?q=non_canonical_start_codon)

but not others (ie, `orf_classification`).

Anyway, until I know what ontology SOFP refers to I won't resolve.  Any ideas?  The warning itself isn't a big deal at all.

**Comment by mdondrup** [comment] 2019-03-18 08:50
First, I should maybe mention that our site has been migrated all the way through since the early days, from Tripal 1 - 2 - 2.1 - 3.1
And in addition we have used the perl chado loader to load our data. Maybe there is some debris there. 

So SOFP is, in fact, a DB? Following your example I did the following:

```
select * from chado.db where name like 'SOFP';
 db_id | name | description | urlprefix | url
-------+------+-------------+-----------+-----
    46 | SOFP |             |           |
(1 row)

licebase_d7=> select DISTINCT cv.name, cvt.name from chado.cv cv INNER JOIN chado.cvterm cvt ON cvt.cv_id = cv.cv_id where cvt.dbxref_id in (SELECT dbx.dbxref_id from chado.dbxref dbx where dbx.db_id = 46);
      name       |           name
------------------+---------------------------
 feature_property | aminoacid
 feature_property | anticodon
 feature_property | chromosome
 feature_property | citation
 feature_property | comment
 feature_property | cyto_range
 feature_property | date
 feature_property | description
 feature_property | dev_stage
 feature_property | dicistronic
 feature_property | element
 feature_property | encoded_symbol
 feature_property | evidenceGB
 feature_property | feature_property
 feature_property | finished
 feature_property | Gap
 feature_property | gbunit
 feature_property | internal_synonym
 feature_property | keywords
 feature_property | linked_to
 feature_property | map
 feature_property | missing_start_codon
feature_property | missing_stop_codon
 feature_property | mol_type
 feature_property | na_change
 feature_property | non_canonical_start_codon
 feature_property | Note
 feature_property | ontology_term
 feature_property | orf_classification
 feature_property | organism
 feature_property | owner
 feature_property | pr_change
 feature_property | problem
 feature_property | protein_id
 feature_property | qseq_type
 feature_property | readthrough_stop_codon
 feature_property | reported_na_change
 feature_property | reported_pr_change
 feature_property | score
 feature_property | source
 feature_property | sp_comment
 feature_property | sp_status
 feature_property | status
 feature_property | symbol
 feature_property | synonym
 feature_property | unixdate
feature_property | Note
 feature_property | ontology_term
 feature_property | orf_classification
 feature_property | organism
 feature_property | owner
 feature_property | pr_change
 feature_property | problem
 feature_property | protein_id
 feature_property | qseq_type
 feature_property | readthrough_stop_codon
 feature_property | reported_na_change
 feature_property | reported_pr_change
 feature_property | score
 feature_property | source
 feature_property | sp_comment
 feature_property | sp_status
 feature_property | status
 feature_property | symbol
 feature_property | synonym
 feature_property | unixdate
 feature_property | validation_flag
 unknown          | is_a
(48 rows)

```

**Comment by bradfordcondon** [comment] 2019-03-18 13:32
I'd agree the most likely cause is custom terms introduced either by the perl loader or an early version of tripal.

```

   SELECT cvt.name, cv.name from db db INNER JOIN dbxref dbx ON dbx.db_id = db.db_id
   INNER JOIN cvterm cvt ON cvt.dbxref_id = dbx.dbxref_id 
   INNER JOIN cv cv ON cvt.cv_id = cv.cv_id
WHERE db.name = 'SOFP';
```

So SOFP is the db, feature_property is the cv.

```
 select * from chado.db2cv_mview where cvname = 'feature_property';
cv_id	cvname	db_id	dbname	num_terms
8	feature_property	1	null	26
(1 row)
drupal=> select * from chado.db2cv_mview where dbname = 'SOFP';
cv_id	cvname	db_id	dbname	num_terms
```

Now we can see in the mview that the feature_property cv is getting linked as null instead of to SOFP.


The actual mview is this:

```
    SELECT DISTINCT CV.cv_id, CV.name as cvname, DB.db_id, DB.name as dbname,
      COUNT(CVT.cvterm_id) as num_terms
    FROM cv CV
      INNER JOIN cvterm CVT on CVT.cv_id = CV.cv_id
      INNER JOIN dbxref DBX on DBX.dbxref_id = CVT.dbxref_id
      INNER JOIN db DB on DB.db_id = DBX.db_id
    WHERE CVT.is_relationshiptype = 0 and CVT.is_obsolete = 0
    GROUP BY CV.cv_id, CV.name, DB.db_id, DB.name
    ORDER BY DB.name
  
```

ok the problem is `CVT.is_relationshiptype = 0`.  

```
select count(*) from chado.cvterm cvt inner join chado.cv ON cv.cv_id = cvt.cv_id INNER JOIN chado.dbxref dbx ON cvt.dbxref_id = dbx.dbxref_id INNER JOIN chado.db db ON db.db_id = dbx.db_id WHERE cv.name = 'feature_property' AND db.name = 'SOFP' AND CVT.is_relationshiptype = 1;
count
47
(1 row)
drupal=> select count(*) from chado.cvterm cvt inner join chado.cv ON cv.cv_id = cvt.cv_id INNER JOIN chado.dbxref dbx ON cvt.dbxref_id = dbx.dbxref_id INNER JOIN chado.db db ON db.db_id = dbx.db_id WHERE cv.name = 'feature_property' AND db.name = 'SOFP' AND CVT.is_relationshiptype = 0;
count
0
(1 row)
```

```
SELECT DISTINCT (db.name) from chado.cvterm cvt inner join chado.cv ON cv.cv_id = cvt.cv_id INNER JOIN chado.dbxref dbx ON cvt.dbxref_id = dbx.dbxref_id INNER JOIN chado.db db ON db.db_id = dbx.db_id WHERE cv.name = 'feature_property' AND CVT.is_relationshiptype = 0;
name
null
(1 row)
drupal=> SELECT DISTINCT (db.name) from chado.cvterm cvt inner join chado.cv ON cv.cv_id = cvt.cv_id INNER JOIN chado.dbxref dbx ON cvt.dbxref_id = dbx.dbxref_id INNER JOIN chado.db db ON db.db_id = dbx.db_id WHERE cv.name = 'feature_property' AND CVT.is_relationshiptype = 1;
name
SOFP
```

So, we've learned that all of the terms attached to SOFP are relationship types and therefore excluded from the mview.

Two questions:


* are the feature_property terms whose db = null SUPPOSED to be SOFP terms?
* SHOULD the db2cv mview actually exclude relationship type terms?  why is it doing that?

**Comment by bradfordcondon** [comment] 2019-03-27 19:29
Wish I had thought to search the legacy codebase before all that digging-

https://github.com/tripal/tripal/blob/7f35a59c5e48bd173d06da51e28d8abbfebc8594/legacy/tripal_feature/files/feature_property.obo



Very few of these terms look like relationship type terms to me.

Those that i consider relationships:

* `linked_to`

Here is what i propose:

Except for the relationship_type terms, create an `update` function that will unset the "is_relationship" value from these terms, then repopulate the mview.  This should resolve the problem.

~~There should be no need to update the base code because this is a legacy OBO (ie, sites migrated from T2 will have this issue).~~ Also need to run this function on install, skipping it if the db/cv combo doesnt exist.

edit: PR submitted doing this.

**Comment by spficklin** [comment] 2019-04-30 21:11
I think this issue is resolved with the PR that was just merged.  If there are outstanding issues please comment.

**Closed as completed by spficklin** 2019-04-30 21:11 UTC
