### ISSUE TITLE
Having TripalDBX compatible with Drupal 10

### ISSUE THREAD

**Issue by guignonv** [tripal/tripal#1378] opened 2023-01-10 12:55 UTC
Several breaking changes in Drupal core (https://www.drupal.org/node/3129492 , https://www.drupal.org/node/2768219) makes current version not compatible with Drupal 10.

The database driver namespace change can be supported if we raise Tripal minimum Drupal version to 9.4.
The per-table prefix support change, however, is more tricky since there were many changes in database Connection class. Since Drupal 10, there is no support for per-table prefixing, therefore they change the way they handle database table prefixing because there is still a support for (all) table prefixing. It needs to be investigated and tested but it will not be simple as we would still support per-table prefixing in Drupal 10 if we want to stay backward compatible with Drupal 9.

Drupal 10 Connection::setPrefix() now only supports string as argument and not array anymore. "tablePlaceholderReplacements" class member must also be initialized while it does not exist in Drupal 9. And there are many other details that are not easily solvable. But it does not appear impossible to do.

Do we want to keep Drupal 9 per-table support and have a different release for Drupal 10? Do we want to drop per-table support and rise minimum requirements to Drupal 9.4? Do we want to back port changes of Drupal 10 Connection into Drupal 9 to have only one branch for both Drupal 9 and 10? Do we have time to spend on that and maintain back ports of future D10 changes into Tripal DBX Connection? ... Discussion is open.

**Comment by laceysanderson** [comment] 2023-01-10 16:56
Thanks for the information @guignonv! 

To my knowledge no one is using per-table prefixing and according to [Drupal.org/Issue2551549](https://www.drupal.org/project/drupal/issues/2551549):

> It has also supported per-table prefixing for about as long. That is so rarely useful that between several long-time devs we could only think of it being used once, and it was a mistake. In practice it's only meaningful use was sharing users across a multi-site, but that is error prone and buggy and with user fields in D8 is basically a no-go now. It's a vestigial feature that serves only to complicate the database layer and code that does low-level things with it.

According to the [changelog](https://www.drupal.org/node/2768219) these are the following reasons that per-table prefixing has been used (generated by users in the previous issue which was open over 3 years) and alternatives to support them:

1. User, session and/or userrole sharing between sites. The alternatives for this are modules that take over the authentication from Drupal core. A few examples of modules that will do that are: [Lightweight Directory Access Protocol (LDAP)](https://www.drupal.org/project/ldap), [CAS](https://www.drupal.org/project/cas), [simpleSAMLphp Authentication](https://www.drupal.org/project/simplesamlphp_auth), [OpenID Connect](https://www.drupal.org/project/openid_connect) and [Bakery Single Sign-On System](https://www.drupal.org/project/bakery).
2. Advanced use-cases where a table needs to be copied or migrated, but you want to use core APIs: for this case you can create a new database connection with a different global prefix, then inject this into the classes you need to use - which will read from the prefixed tables
3. Content and/or config synchronization between sites. Config synchronization is supported by Drupal core. See https://www.drupal.org/documentation/administer/config for more info. Content synchronization is a bit more difficult. At the moment we have an initiative for supporting content synchronization in Drupal core. See [#2721129: Workflow Initiative](https://www.drupal.org/project/ideas/issues/2721129) and http://buytaert.net/improving-drupal-content-workflow for more info. An alternative is to use the [domain](https://www.drupal.org/project/domain) module. It uses a low-key way of of sharing content between sites. Yet an other alternative is the [deploy](https://www.drupal.org/project/deploy) module. It uses a high-level content staging mechanism to copy content between sites.

**Comment by laceysanderson** [comment] 2023-01-10 16:59
I believe we should drop support for per-table prefixing in all version of Tripal 4 (Drupal 9 + 10) and am content requiring a minimum version of 9.4.x (we currently show support for 9.3.x via testing, 9.2.x support is minimal and only for PHP 8.0).

I believe the above use cases apply even less to Tripal sites thanks to PostgreSQL support for multiple schema among other reasons.

**Comment by laceysanderson** [comment] 2023-01-10 17:01
Moving this to the Tripal repository for greater exposure and since this will not be addressed before the alpha release.

**Comment by guignonv** [comment] 2023-01-12 09:39
OK, I'll assume we raise the minimum requirement to 9.4 and see what can be done to have only one branch to maintain.

**Comment by laceysanderson** [comment] 2023-05-15 15:48
We noticed in the postgresql documentation that pg_temp may not always exist:

> Likewise, the current session's temporary-table schema, pg_temp_nnn, is always searched if it exists. It can be explicitly listed in the path by using the alias pg_temp. If it is not listed in the path then it is searched first (even before pg_catalog). However, the temporary schema is only searched for relation (table, view, sequence, etc.) and data type names. It is never searched for function or operator names.

https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-SEARCH-PATH

We have not found documentation saying exactly when it may not exist but we suspect that it only exists when it is needed. This is session dependant (i.e. there is a pg_temp per session currently open).

The following function will test if it exists:

```sql
SELECT pg_my_temp_schema();
```

It may simply be that we need to create something temporary to have it created but as of yet, we are not sure. If this is the case, something like the following would accomplish that (to be added at the beginning of TripalDBX/pg-clone-schema/clone_schema.sql).

```sql
CREATE TEMPORARY TABLE IF NOT EXISTS tripal_dbx_clone_temp();
```

PS. The cloning functions are now stored in pg_temp on an as needed basis as compared to in the public schema on install of tripal.

**Comment by laceysanderson** [comment] 2023-05-15 18:35
**NOTE: This problem will be fixed in the next commit on this branch but I'm including my train of thought here in case my digging through the Drupal stack on how connection object are created is helpful to someone in the future.**

The problem was that Drupal was prefixing with a fixed `chado.` when you initialized a chado connection and then your query included Drupal tables.

The specific example: $connection->findVersion() generates a query selecting from the Drupal chado_installations table and this is what we were seeing:
```
❯ docker exec -it testing-1378 drush php:cli
Psy Shell v0.11.17 (PHP 8.1.19 — cli) by Justin Hileman
Tripal 4 on Drupal 9 DEVELOPMENT (Drupal 10.0.10-dev)
> $connection = \Drupal::service('tripal_chado.database');
= Drupal\tripal_chado\Database\ChadoConnection {#7282}

> $connection->findVersion();

   Drupal\Core\Database\DatabaseExceptionWrapper  SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "chado.chado_installations" does not exist
LINE 3: "chado"."chado_installations" "i"
        ^: SELECT "i"."version" AS "version"
FROM
"chado"."chado_installations" "i"
WHERE "schema_name" = :db_condition_placeholder_0; Array
(
    [:db_condition_placeholder_0] => chado
).
```

All prefixing of {tablename} and {1:tablename} happen in the `TripalDbxConnection->prefixTables()` function which takes an SQL statement in as a variable.

I confirmed that `TripalDbxConnection->prefixTables()` does not make any changes to {DrupalTableNames} but instead calls `parent::prefixTables($sql)` at the bottom of its version to pass any unmodified {tablenames} to Drupal to handle.

The parent of TripalDbxConnection is the postgresql version of the connection object: [\Drupal\pgsql\Driver\Database\pgsql\Connection](https://api.drupal.org/api/drupal/core%21modules%21pgsql%21src%21Driver%21Database%21pgsql%21Connection.php/class/Connection/10).

However, pgsql\Connection does not implement prefixTables(). Therefore we need to look to its parent \Drupal\Core\Database\Connection (which you cannot see on the Drupal api site 🤔 but is at core/lib/Drupal/Core/Database/Connection.php).

This is the core Drupal database Connection implementation which TripalDbxConnection->prefixTables calls:

```php
public function prefixTables($sql) {
  return str_replace({'{', '}'], $this->tablePlaceholderReplacements, $sql);
}
```

So, who is `tablePlaceholderReplacements`? It is a private variable (so cannot be accessed by any of it's descendants) and is only set by setPrefix().

```php
  /**
   * Set the prefix used by this database connection.
   *
   * @param string $prefix
   *   A single prefix.
   */
  protected function setPrefix($prefix) {
    assert(is_string($prefix), 'The \'$prefix\' argument to ' . __METHOD__ . '() must be a string');
    $this->prefix = $prefix;
    $this->tablePlaceholderReplacements = [
      $this->identifierQuotes[0] . str_replace('.', $this->identifierQuotes[1] . '.' . $this->identifierQuotes[0], $prefix),
      $this->identifierQuotes[1],
    ];
  }
```

Okay, so where is setPrefix called? It is called in the __construct and set as follows:
```php
$this->setPrefix($connection_options['prefix]);
```
where $connection_options is passed into the contructor and contains the prefix, namespace and other driver-specific options.

When I create a chado connection, my prefix is set to `chado.` Note: this happens all the time, even when there is no `chado` named schema (i.e. when chado is installed in `testchado` or when chado is not yet installed).
Ok, so how are database connections created (i.e. when is the constructor called and who sets these parameters?)

In the core Drupal services.yml we see this:
```lml
database:
    class: Drupal\Core\Database\Connection
    factory: [Drupal\Core\Database\Database::getConnection](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Database%21Database.php/function/Database%3A%3AgetConnection/10)
    arguments: [default]
```

which means that the static getConnection class is the one providing our options and calling the constructor. Specifically, when connections are created, Database::getConnection() is called with the database name and key in settings.php. We don't set these in the services.yml therefore it is set to default and "the active key" by default.

In the code of Database::getConnection() it says:
```php
// By default, we want the active connection, set in setActiveConnection.
$key = self::$activeKey;
```

Okay, so now we check settings.yml to see what the active key is. However, we found out that the only key in there is the default-default key for the Drupal database...

Okay, so then we must be programatically altering that somewhere... 🤔 and found it! In the TripalDbxConnection constructor we were setting the prefix incorrectly. The bug was fixed by removing this block of code:
```diff
diff --git a/tripal/src/TripalDBX/TripalDbxConnection.php b/tripal/src/TripalDBX/TripalDbxConnection.php
index c8896c677..3bc6dcb4e 100644
--- a/tripal/src/TripalDBX/TripalDbxConnection.php
+++ b/tripal/src/TripalDBX/TripalDbxConnection.php
@@ -334,34 +334,6 @@ abstract class TripalDbxConnection extends PgConnection {
     // Get option array.
     $connection_options = $database->getConnectionOptions();
     $this->databaseName = $connection_options['database'];
-    // Check if a Tripal DBX managed schema name has been specified.
-    if (!empty($schema_name)) {
-      // We must use this PostgreSQL schema instead of the Drupal one as default
-      // for this database connection. To do so, we use the schema name as a
-      // prefix (which is supported by Drupal PostgreSQL implementation).
-      // Note: if the schema name is not valid, an exception will be thrown by
-      // setSchemaName() at the end of this constructor.
-      $connection_options['prefix'] = $schema_name . '.';
-      // Add search_path to avoid the use of Drupal schema by mistake.
-      [$start_quote, $end_quote] = $this->identifierQuotes;
-      // Set Tripal DBX managed schema name first.
-      $connection_options['init_commands']['search_path'] =
-        'SET search_path='
-        . $start_quote
-        . $schema_name
-        . $end_quote
-      ;
-      // Then add Drupal schema.
-      $drupal_schema = $this->tripalDbxApi->getDrupalSchemaName();
-      if (!empty($drupal_schema)) {
-        $connection_options['init_commands']['search_path'] .=
-          ','
-          . $start_quote
-          . $drupal_schema
-          . $end_quote
-        ;
-      }
-    }
 
     // Get a new connection distinct from Drupal's to avoid search_path issues.
     $connection = static::openNewPdoConnection($database);
```

**Comment by guignonv** [comment] 2023-05-15 19:05
The above code that has been removed, was initially there to set a default behavior: the purpose was to use the given schema as default schema when no schema prefix was given in queries (ie. "{table_name}" or even just "table_name" instead of "{#:table_name}") but it appeared later in the development that this behavior was not a good idea. In the real world, the "external" connection is sometimes passed to Drupal components that are not aware the default schema is not Drupal's and will expect it to work on Drupal's schema. It would raise errors. That's why the set of functions "useTripalDbxSchemaFor", "useDrupalSchemaFor" and "shouldUseTripalDbxSchema" were created and table with no schema identifier should use Drupal schema's as default. So that piece of code should have been removed a long time ago (but I forgot....). ;p

**Comment by laceysanderson** [comment] 2023-05-15 23:07
Both install and prepare for chado now work on Drupal 10! And only 9 tests are failing 🤪 https://github.com/tripal/tripal/actions/runs/4985835918/jobs/8925914656

**Comment by laceysanderson** [comment] 2023-05-16 17:19
This has been taking a lot of rebuilding of the same image/container ;-p So I'm just going to keep this here for easy copy/paste.

```
docker build --tag=tripaldocker:testD10 --build-arg drupalversion="10.0.x-dev" --build-arg chadoschema=testchado --file tripaldocker/Dockerfile-php8.1-pgsql13 ./
docker run --publish=80:80 --name=testD10 -tid --volume=`pwd`:/var/www/drupal9/web/modules/contrib/tripal tripaldocker:testD10
docker exec testD10 service postgresql restart
docker exec --workdir=/var/www/drupal9/web/modules/contrib/tripal testD10 phpunit tripal/tests/src/Functional/TripalDBX/ConnectionTest.php
```

**Comment by laceysanderson** [comment] 2023-05-29 17:11
This was fixed with the linked PR merge. Any outstanding issues are in Issue #1523.

**Closed as completed by laceysanderson** 2023-05-29 17:11 UTC
Labels: Community - Discussion, PMC - Discussion, Group 2 - Data Storage | Tripal DBX | Chado
