### ISSUE TITLE
unable to publish many content types due to no module widget callback

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#852] opened 2019-02-13 15:57 UTC
## BUG/ERROR report
I'm currently unable to publish most content types on my site.

undefined function `_field_widget_form()` in `tripal_chado.publish.inc` line 96.

<img width="1274" alt="screen shot 2019-02-13 at 10 54 36 am" src="https://user-images.githubusercontent.com/7063154/52724700-d86dc200-2f7d-11e9-8f2f-d3ab471b5550.png">

It seems the only content i don't have this error for is project.

https://github.com/tripal/tripal/blob/52bec75150e4518b3f617c179abc34105d1cdaba/tripal_chado/includes/tripal_chado.publish.inc#L91-L97

here are some `$instance`s that will trigger this error:

<img width="1010" alt="screen shot 2019-02-13 at 11 01 07 am" src="https://user-images.githubusercontent.com/7063154/52725212-be80af00-2f7e-11e9-90e3-d811dd34212d.png">

<img width="870" alt="screen shot 2019-02-13 at 11 01 21 am" src="https://user-images.githubusercontent.com/7063154/52725234-ca6c7100-2f7e-11e9-9e7a-a6b7b422fef8.png">

in both cases, $instance['widget']['module'] is null.
The obvious workaround is to wrap the callback function in something like ` if (!$instance['widget']['module']) {}` so we dont get this error.  But considering this error just popped up for me, im wondering if something has gone wrong...

**Comment by laceysanderson** [comment] 2019-03-20 22:20
Hmmm.... I just tested this on a new Tripal site and am not able to reproduce. Specifically, I published analysis, genes and cultivars. In all three cases `$instance['widget']['module']` is correctly set to `tripal`. Are you still experiencing this problem @bradfordcondon ?

**Comment by bradfordcondon** [comment] 2019-03-21 00:05
no, but i never figured out what caused the issue :|

**Comment by spficklin** [comment] 2019-04-23 21:45
This fix got merged, so I'm closing.

**Closed as completed by spficklin** 2019-04-23 21:45 UTC
Labels: bug - confirmed
